[project]
name = "python-lib"
version = "0.0.0"
description = "My sample Python library"
readme = "README.md"
authors = [{ name = "Gianluca Costa", email = "gianluca@gianlucacosta.info" }]
requires-python = ">=3.12"
dependencies = ["info-gianlucacosta-iris==4.0.1"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pdm]
distribution = true

[tool.pdm.scripts]
verify = "echo '🐍📃 pyproject.toml `verify` script!'"
