name: Test check-rust-versions

runs:
  using: composite
  steps:
    - name: Checking Rust versions for Rust crate should work
      uses: ./actions/check-rust-versions
      with:
        project-directory: ./tests/rust-crate

    - name: Checking Rust versions for Rust web assembly should work
      uses: ./actions/check-rust-versions
      with:
        project-directory: ./tests/rust-wasm
