name: Check artifact version
description: Ensures the artifact version matches the current branch version.

inputs:
  project-directory:
    description: The directory containing the project.
    required: false
    default: .

  shell:
    description: The shell used to run commands.
    required: false
    default: bash

runs:
  using: composite
  steps:
    - name: Detect project type
      id: detect-project-tech
      uses: giancosta86/aurora-github/detect-project-tech@b2.0.0
      with:
        project-directory: ${{ inputs.project-directory }}
        shell: ${{ inputs.shell }}

    - name: Detect branch and version
      id: detect-branch-version
      uses: giancosta86/aurora-github/detect-branch-version@b2.0.0
      with:
        shell: ${{ inputs.shell }}

    - name: Check Rust crate version
      if: ${{ steps.detect-project-tech.outputs.project-tech == 'rust' }}
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: grep -q "^version\s*=\s*\"${{ detect-branch-version.outputs.version }}\"" Cargo.toml

    - name: Check NodeJS package version
      if: ${{ steps.detect-project-tech.outputs.project-tech == 'nodejs' }}
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: grep -q '\"version\"\s*:\s*\"${{ detect-branch-version.outputs.version }}\"' package.json

    - name: Fail on unknown project tech
      if: ${{ steps.detect-project-tech.outputs.project-tech == '' }}
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: |
        echo "❌Cannot validate the artifact version for an unknown project type" >&2
        exit 1
