name: Test find-regex-pattern
description: Tests for find-regex-pattern.

runs:
  using: composite
  steps:
    - uses: giancosta86/gauntlet/actions/setup-elvish-action@v1

    - shell: elvish {0}
      run: echo 🎭 Looking for matching pattern...

    - uses: ./actions/find-regex-pattern
      id: find-matching-pattern
      with:
        working-directory: tests/unknown-tech/src
        files: "*.txt"
        regex: TO.O!

    - uses: ./actions/run-elvish-tests
      with:
        working-directory: ${{ github.action_path }}
        velvet-scripts: matching
      env:
        found: ${{ steps.find-matching-pattern.outputs.found }}

    - shell: elvish {0}
      run: echo 🎭 Looking for missing pattern...

    - uses: ./actions/find-regex-pattern
      id: look-for-missing-pattern
      with:
        files: tests/unknown-tech/src/*.txt
        regex: SOMETHING-ELSE
        crash-when: not-found

    - uses: ./actions/run-elvish-tests
      with:
        working-directory: ${{ github.action_path }}
        velvet-scripts: missing
      env:
        found: ${{ steps.look-for-missing-pattern.outputs.found }}
