name: Test inject-branch-version and check-artifact-version

runs:
  using: composite
  steps:
    - uses: ./actions/detect-branch-version
      id: version-detector

    - name: Inject version into 🦀Rust crate
      uses: ./actions/inject-branch-version
      with:
        artifact-file: ./tests/rust-crate/Cargo.toml

    - name: Inject version into 📦NodeJS package
      uses: ./actions/inject-branch-version
      with:
        artifact-file: ./tests/npm-package/package.json

    - name: Display updated artifacts
      shell: bash
      run: |
        echo "🦀Rust descriptor:"
        less ./tests/rust-crate/Cargo.toml

        echo "📦NodeJS descriptor:"
        less ./tests/npm-package/package.json

    - uses: ./actions/check-artifact-version
      with:
        project-directory: ./tests/rust-crate

    - uses: ./actions/check-artifact-version
      with:
        project-directory: ./tests/npm-package
