name: Test inject-branch-version and check-artifact-version

runs:
  using: composite
  steps:
    - uses: ./actions/detect-branch-version
      id: version-detector

    - name: Inject version into Rust crate
      uses: ./actions/inject-branch-version
      with:
        project-directory: ./tests/rust-crate

    - name: Display updated Rust crate descriptor
      shell: bash
      working-directory: tests/rust-crate
      run: |
        echo "🦀Rust crate descriptor:"
        less Cargo.toml
        echo "🦀🦀🦀"

    - name: Inject version into Rust web assembly
      uses: ./actions/inject-branch-version
      with:
        project-directory: ./tests/rust-wasm

    - name: Display updated Rust web assembly descriptor
      shell: bash
      working-directory: tests/rust-wasm
      run: |
        echo "🦀Rust 🌐web assembly descriptor:"
        less Cargo.toml
        echo "🦀🦀🦀"

    - name: Inject version into NodeJS package
      uses: ./actions/inject-branch-version
      with:
        project-directory: ./tests/npm-package

    - name: Display updated NodeJS package descriptor
      shell: bash
      working-directory: tests/npm-package
      run: |
        echo "📦NodeJS descriptor:"
        less package.json
        echo "📦📦📦"

    - name: Inject version into unknown project
      uses: ./actions/inject-branch-version
      with:
        artifact-descriptor: some-descriptor.txt
        project-directory: ./tests/unknown-tech

    - name: Display updated unknown tech descriptor
      shell: bash
      working-directory: tests/unknown-tech
      run: |
        echo "🎁Unknown tech descriptor:"
        less some-descriptor.txt
        echo "🎁🎁🎁"

    - name: Version should appear correctly in Rust crate
      uses: ./actions/check-artifact-version
      with:
        project-directory: ./tests/rust-crate

    - name: Version should appear correctly in Rust wasm
      uses: ./actions/check-artifact-version
      with:
        project-directory: ./tests/rust-wasm

    - name: Version should appear correctly in npm package
      uses: ./actions/check-artifact-version
      with:
        project-directory: ./tests/npm-package

    - name: Version should appear correctly in unknown descriptor
      shell: bash
      working-directory: tests/unknown-tech
      run: |
        version="${{ steps.version-detector.outputs.version }}"

        if ! cat some-descriptor.txt | grep -q "v$version"
        then
          echo "❌Error while injecting the version into a custom descriptor!" >&2
          exit 1
        fi

    - name: Version should be injected multiple times
      shell: bash
      working-directory: tests/unknown-tech
      run: |
        version="${{ steps.version-detector.outputs.version }}"

        if ! cat some-descriptor.txt | grep -q "'$version';"
        then
          echo "❌The version was not injected multiple times into a custom descriptor!" >&2
          exit 1
        fi
