name: Test publish-jvm-project
description: Tests for publish-jvm-project.

inputs:
  jvm-token:
    description: Token used when publishing to a Maven repo.

runs:
  using: composite
  steps:
    - uses: ./actions/init-aurora-github

    - shell: elvish {0}
      run: echo 🎭 Testing publication via Maven...

    - uses: ./actions/publish-jvm-project
      with:
        working-directory: tests/maven-project
        auth-user: gian-token
        auth-token: ${{ inputs.jvm-token }}

    - shell: elvish {0}
      run: echo 🎭 Testing publication via Gradle...

    - uses: ./actions/publish-jvm-project
      with:
        working-directory: tests/gradle-project
        auth-user: gian-token
        auth-token: ${{ inputs.jvm-token }}

    - shell: elvish {0}
      run: echo ✅ All tests OK!
