name: Check subpath exports
description: Verifies that all the subpath exports in package.json actually match existing files.

inputs:
  project-directory:
    description: The directory containing `package.json`.
    default: .

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v11.0.0

    - shell: elvish {0}
      working-directory: ${{ inputs.project-directory }}
      run: |
        use aurora-github/nodejs/subpath-exports

        subpath-exports:check
