name: Check subpath exports
description: Verifies that all the subpath exports in package.json actually match existing files.

inputs:
  working-directory:
    description: Directory containing `package.json`.
    default: .

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/init-aurora-github@v11.0.1

    - shell: elvish {0}
      working-directory: ${{ inputs.working-directory }}
      run: |
        use github.com/giancosta86/aurora-github/actions/check-subpath-exports
        check-subpath-exports:main
