name: Test check-subpath-exports

runs:
  using: composite
  steps:
    - uses: ./.github/test-actions/test-check-subpath-exports/scenario
      with:
        header: Test when the "exports" field is missing...
        jq-operation: del(.exports)

    - uses: ./.github/test-actions/test-check-subpath-exports/scenario
      with:
        header: Test when the "exports" field is present but empty...
        jq-operation: .exports={}

    - uses: ./.github/test-actions/test-check-subpath-exports/scenario
      with:
        header: Test when the "exports" field is a string...
        jq-operation: .exports="./src/beta/index.js"

    - uses: ./.github/test-actions/test-check-subpath-exports/scenario
      with:
        header: Test when the "exports" field contains a string field...
        jq-operation: |
          .exports={
            "beta": "./src/beta/index.js"
          }

    - uses: ./.github/test-actions/test-check-subpath-exports/scenario
      with:
        header: Test when the "exports" field contains an object field...
        jq-operation: |
          .exports={
              "beta": {
                "import": "./src/beta/index.js",
                "default": "./src/beta/index.js"
              }
            }

    - uses: ./.github/test-actions/test-check-subpath-exports/scenario
      with:
        header: Test when the "exports" field contains multiple fields...
        jq-operation: |
          .exports={
              "alpha": {
                "import": "./src/alpha/index.ts",
                "default": "./src/alpha/index.ts"
              },

              "beta": {
                "import": "./src/beta/index.js",
                "default": "./src/beta/index.js"
              },

              "omega": "./src/omega/index.ts"
            }
