name: Test verify-jvm-project

runs:
  using: composite
  steps:
    - shell: bash
      run: echo "🎭Displaying JVM versions..."

    - shell: bash
      run: |
        echo "☕Java version: $(java --version | head -n 1)"

        echo "🪶Maven version: $(mvn --version | head -n 1)"

        echo "🐘Gradle version: $(gradle --version | grep -P '^Gradle \d+\.\d+(\.\d+)?$' | head -n 1 | cut -d ' ' -f 2)"

    - uses: ./actions/detect-branch-version
      id: version-detector

    - shell: bash
      run: echo "🎭Build and verify the Maven project..."

    - uses: ./actions/verify-jvm-project
      with:
        project-directory: tests/maven-project

    - name: Run the Maven-generated jar
      shell: bash
      working-directory: tests/maven-project
      run: |
        version="${{ steps.version-detector.outputs.version }}"

        programOutput="$(java -jar target/maven-project-$version.jar)"

        echo "🔎Maven program output: '$programOutput'"

        if [[ "$programOutput" == "Hello, world - from Kotlin! 🥳" ]]
        then
          echo "🪶Maven project verified and run successfully!"
        else
          echo "❌Unexpected program output!" >&2
          exit 1
        fi

    - shell: bash
      run: echo "🎭Build and verify the Gradle project..."

    - name: Build and verify the Gradle project
      uses: ./actions/verify-jvm-project
      with:
        project-directory: tests/gradle-project

    - name: Run the Gradle-generated jar
      shell: bash
      working-directory: tests/gradle-project
      run: |
        version="${{ steps.version-detector.outputs.version }}"

        programOutput="$(java -jar build/libs/gradle-project-$version.jar)"

        echo "🔎Gradle program output: '$programOutput'"

        if [[ "$programOutput" == "Hello, world - from Kotlin! 🥳" ]]
        then
          echo "🐘Gradle project verified and run successfully!"
        else
          echo "❌Unexpected program output!" >&2
          exit 1
        fi
