name: Test verify-jvm-project
description: Tests for verify-jvm-project.

runs:
  using: composite
  steps:
    - uses: ./actions/init-aurora-github

    - shell: bash
      working-directory: ${{ github.action_path }}
      run: elvish setup.elv

    - uses: ./actions/detect-branch-version
      id: version-detector

    - shell: elvish {0}
      run: echo 🎭 Verifying the Maven project...

    - uses: ./actions/verify-jvm-project
      with:
        working-directory: tests/maven-project
        check-license: false

    - shell: elvish {0}
      run: echo 🎭 Verifying the Gradle project...

    - uses: ./actions/verify-jvm-project
      with:
        working-directory: tests/gradle-project
        check-license: false

    - shell: elvish {0}
      run: echo 🎭 Checking the action effects...

    - uses: ./actions/run-elvish-tests
      with:
        working-directory: ${{ github.action_path }}
        velvet-scripts: action
      env:
        version: ${{ steps.version-detector.outputs.version }}

    - shell: elvish {0}
      run: echo ✅ All tests OK!
