name: Test verify-rust-wasm
description: Tests for verify-rust-wasm.

runs:
  using: composite
  steps:
    - uses: giancosta86/gauntlet/actions/setup-elvish-action@v1

    - shell: elvish {0}
      run: echo 🎭 Running with npm cope...

    - uses: ./actions/verify-rust-wasm
      with:
        working-directory: tests/rust-wasm
        wasm-pack-version: 0.15.0
        npm-scope: giancosta86
        node-version: 26.2.0
        package-manager: pnpm@10.22.0

    - shell: elvish {0}
      run: echo 🎭 Running with <ROOT> pseudo-scope...

    - uses: ./actions/verify-rust-wasm
      with:
        working-directory: tests/rust-wasm
        wasm-pack-version: 0.15.0
        npm-scope: <ROOT>
        node-version: 26.2.0
        package-manager: pnpm@10.22.0

    - shell: elvish {0}
      run: echo ✅ All tests OK!
