name: Test publish-python-package
description: Tests for publich-python-package.

inputs:
  index-secret:
    description: Password/token for publishing to the index.

runs:
  using: composite
  steps:
    - uses: ./actions/publish-python-package
      with:
        pdm-version: 2.28.0

        index-url: https://repo.repsy.io/giancosta86/pyground/simple

        index-user: gian-token

        index-secret: ${{ inputs.index-secret }}

        working-directory: tests/python-lib
