name: Publish GitHub Pages
description: Publishes a directory as the GitHub Pages website for the current repository.

inputs:
  source-directory:
    description: Directory containing the website.
    default: .

  optional:
    description: Whether "source-directory" can be empty string or missing directory.
    default: false

  enforce-branch-version:
    description: How the branch version should be enforced.
    default: inject

  dry-run:
    description: Stop the publication just before uploading.
    default: false

outputs:
  url:
    description: The URL of the published website.
    value: ${{ steps.publish-pages.outputs.page_url }}

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v10.3.0

    - name: Set up strategy
      shell: elvish {0}
      run: |
        use aurora-github/input
        use aurora-github/pages

        var source-directory = (input:require source-directory '${{ inputs.source-directory }}')
        var optional = (input:require-bool optional '${{ inputs.optional }}')

        pages:detect-strategy-from-sources $source-directory $optional

    - name: Enforce branch version
      if: env.strategy == 'nodejs' || env.strategy == 'maven'
      uses: giancosta86/aurora-github/actions/enforce-branch-version@v10.3.0
      with:
        mode: ${{ inputs.enforce-branch-version }}
        project-directory: ${{ inputs.source-directory }}

    - name: Setup NodeJS context
      if: env.strategy == 'nodejs'
      uses: giancosta86/aurora-github/actions/setup-nodejs-context@v10.3.0
      with:
        project-directory: ${{ inputs.source-directory }}

    - name: Create the website via NodeJS
      if: env.strategy == 'nodejs'
      shell: elvish {0}
      run: |
        use aurora-github/input
        use aurora-github/pages

        pages:build-via-nodejs (input:require source-directory '${{ inputs.source-directory }}')

    - name: Create the website via Maven
      if: env.strategy == 'maven'
      shell: elvish {0}
      run: |
        use aurora-github/input
        use aurora-github/pages

        pages:build-via-maven (input:require source-directory '${{ inputs.source-directory }}')

    - name: Setup static artifacts
      if: env.strategy == 'static-files'
      shell: elvish {0}
      run: |
        use aurora-github/input
        use aurora-github/pages

        pages:set-artifact-directory (input:require source-directory '${{ inputs.source-directory }}')

    - name: Check artifacts
      if: env.strategy != 'exit'
      shell: elvish {0}
      run: |
        use aurora-github/input
        use aurora-github/pages

        var optional = (input:require-bool optional '${{ inputs.optional }}')

        pages:check-artifact-directory (get-env artifactDirectory) $optional

    - name: Skip publication on dry-run
      if: env.strategy != 'exit'
      shell: elvish {0}
      run: |
        use aurora-github/input
        use aurora-github/pages

        var dry-run = (input:require-bool dry-run '${{ inputs.dry-run }}')

        pages:skip-publication-on-dry-run $dry-run

    - name: Upload website artifacts
      if: env.strategy != 'exit'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ env.artifactDirectory }}

    - name: Publish website via GitHub Pages
      if: env.strategy != 'exit'
      id: publish-pages
      uses: actions/deploy-pages@v4

    - name: Print confirmation message
      if: env.strategy != 'exit'
      shell: elvish {0}
      run: |
        echo ✅Publication to GitHub Pages successful!
        echo 🌐Website: ${{ steps.publish-pages.outputs.page_url }}
