name: Publish GitHub Pages
description: Publishes a directory as the GitHub Pages website for the current repository.

inputs:
  source-directory:
    description: Directory containing the website.
    default: .

  optional:
    description: Whether `source-directory` can be empty string or missing directory.
    default: false

  enforce-branch-version:
    description: How the branch version should be enforced.
    default: inject

  dry-run:
    description: Stop the publication just before uploading.
    default: false

outputs:
  url:
    description: The URL of the published website.
    value: ${{ steps.publish-pages.outputs.page_url }}

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v11.0.0

    - name: Set up strategy
      shell: elvish {0}
      run: |
        use aurora-github/ci-cd/input
        use aurora-github/website

        var optional = (input:bool optional '${{ inputs.optional }}')

        var source-directory = (input:directory &optional=$optional &can-be-missing=$optional source-directory '${{ inputs.source-directory }}')

        website:detect-strategy-from-sources $source-directory

    - name: Enforce branch version
      if: env.strategy == 'nodejs' || env.strategy == 'maven'
      uses: giancosta86/aurora-github/actions/enforce-branch-version@v11.0.0
      with:
        mode: ${{ inputs.enforce-branch-version }}
        working-directory: ${{ inputs.source-directory }}

    - name: Setup NodeJS context
      if: env.strategy == 'nodejs'
      uses: giancosta86/aurora-github/actions/setup-nodejs-context@v11.0.0
      with:
        working-directory: ${{ inputs.source-directory }}

    - name: Create the website via NodeJS
      if: env.strategy == 'nodejs'
      shell: elvish {0}
      run: |
        use aurora-github/ci-cd/input
        use aurora-github/website

        website:build-via-nodejs (input:string source-directory '${{ inputs.source-directory }}')

    - name: Create the website via Maven
      if: env.strategy == 'maven'
      shell: elvish {0}
      run: |
        use aurora-github/ci-cd/input
        use aurora-github/website

        website:build-via-maven (input:string source-directory '${{ inputs.source-directory }}')

    - name: Setup static artifacts
      if: env.strategy == 'static-files'
      shell: elvish {0}
      run: |
        use aurora-github/ci-cd/input
        use aurora-github/website

        website:set-artifact-directory (input:string source-directory '${{ inputs.source-directory }}')

    - name: Check artifacts
      if: env.strategy != 'exit'
      shell: elvish {0}
      run: |
        use aurora-github/ci-cd/input
        use aurora-github/website

        var optional = (input:bool optional '${{ inputs.optional }}')

        website:check-artifact-directory (get-env artifactDirectory) $optional

    - name: Skip publication on dry-run
      if: env.strategy != 'exit'
      shell: elvish {0}
      run: |
        use aurora-github/ci-cd/input
        use aurora-github/website

        var dry-run = (input:bool dry-run '${{ inputs.dry-run }}')

        website:skip-publication-on-dry-run $dry-run

    - name: Upload website artifacts
      if: env.strategy != 'exit'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ env.artifactDirectory }}

    - name: Publish website via GitHub Pages
      if: env.strategy != 'exit'
      id: publish-pages
      uses: actions/deploy-pages@v4

    - name: Print confirmation message
      if: env.strategy != 'exit'
      shell: elvish {0}
      run: |
        use github.com/giancosta86/aurora-elvish/console

        console:echo ✅ Website publication successful!
        console:echo 🌐 Project website: ${{ steps.publish-pages.outputs.page_url }}
