name: Publish npm package
description: Publishes a NodeJS package to the npm registry.

inputs:
  npm-token:
    description: The secret token for publishing to npm.
    required: true

  frozen-lockfile:
    description: Fails if 'pnpm-lock.yaml' is missing or outdated.
    required: false
    default: true

  project-directory:
    description: The directory containing package.json.
    required: false
    default: .

  shell:
    description: The shell used to run commands.
    required: false
    default: bash

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Setup NodeJS and NPM registry
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.project-directory }}/.nvmrc
        registry-url: https://registry.npmjs.org
        cache: pnpm

    - name: Install production-only dependencies
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: |
        frozenLockfile="${{ inputs.frozen-lockfile }}"

        if [[ $frozenLockfile == "true" ]]
        then
          pnpm install --prod --frozen-lockfile
        else
          pnpm install --prod --no-frozen-lockfile
        fi

    - name: Publish to npm
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: pnpm publish --no-git-checks --access public
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
