name: Publish npm package
description: Publish a NodeJS package to the npm registry.

inputs:
  npm-token:
    description: The secret token for publishing to npm.
    required: true

  pnpm-version:
    description: The version of pnpm to use.
    required: false
    default: 9

  project-directory:
    description: The directory containing package.json.
    required: false
    default: .

  shell:
    description: The shell used to run commands.
    required: false
    default: bash

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup NodeJS and NPM registry
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.project-directory }}/.nvmrc
        registry-url: https://registry.npmjs.org
        cache: pnpm

    - name: Install dependencies
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: pnpm install --frozen-lockfile

    - name: Publish to npm
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: pnpm publish --no-git-checks --access public
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
