name: Publish npm package
description: Publishes a NodeJS package to an npm registry.

inputs:
  dry-run:
    description: Run a simulated publication.
    default: false

  npm-token:
    description: Secret token for publishing to the registry.

  working-directory:
    description: Directory containing `package.json`.
    default: .

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/init-aurora-github@v12.0.0

    - uses: giancosta86/aurora-github/actions/inject-branch-version@v12.0.0
      with:
        files: package.json
        working-directory: ${{ inputs.working-directory }}

    - uses: giancosta86/aurora-github/actions/setup-nodejs-context@v12.0.0
      with:
        working-directory: ${{ inputs.working-directory }}

    - shell: elvish {0}
      working-directory: ${{ inputs.working-directory }}
      run: |
        use github.com/giancosta86/aurora-github/actions/publish-npm-package
        publish-npm-package:main
      env:
        dry-run: ${{ inputs.dry-run }}
        NPM_TOKEN: ${{ inputs.npm-token }}
