name: Publish npm package
description: Publishes a NodeJS package to the npm registry.

inputs:
  dry-run:
    description: Run a simulated publication via --dry-run.
    required: false
    default: false

  npm-token:
    description: The secret token for publishing to npm.
    required: true

  frozen-lockfile:
    description: Fail if 'pnpm-lock.yaml' is missing or outdated.
    required: false
    default: true

  project-directory:
    description: The directory containing package.json.
    required: false
    default: .

  shell:
    description: The shell used to run commands.
    required: false
    default: bash

runs:
  using: composite
  steps:
    - name: Validate inputs
      shell: ${{ inputs.shell }}
      run: |
        if [[ -z "${{ inputs.dry-run }}" ]]
        then
          echo "❌Missing action input: 'dry-run'!" >&2
          exit 1
        fi

        if [[ ${{ inputs.dry-run }} != 'true' && -z "${{ inputs.npm-token }}" ]]
        then
          echo "❌Missing action input: 'npm-token'!" >&2
          exit 1
        fi

        if [[ -z "${{ inputs.frozen-lockfile }}" ]]
        then
          echo "❌Missing action input: 'frozen-lockfile'!" >&2
          exit 1
        fi

    - name: Setup NodeJS and NPM registry
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.project-directory }}/.nvmrc
        registry-url: https://registry.npmjs.org

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Install dependencies
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: |
        frozenLockfile="${{ inputs.frozen-lockfile }}"

        if [[ "$frozenLockfile" == "true" ]]
        then
          pnpm install --frozen-lockfile
        else
          pnpm install --no-frozen-lockfile
        fi

    - name: Display the artifact descriptor
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: |
        echo "The content of your 📦package.json just before publication is:"
        jq . package.json

    - name: Publish to npm
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: |
        dryRun="${{ inputs.dry-run }}"

        if [[ "$dryRun" == "true" ]]
        then
          pnpm publish --no-git-checks --access public --dry-run
        else
          pnpm publish --no-git-checks --access public
        fi
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
