name: Test run-custom-tests

runs:
  using: composite
  steps:
    - uses: ./.github/test-actions/test-run-shell-script/scenario
      with:
        script-base: bash-test
        script-extension: .sh
        shell: bash
        multiplier: 10

    - uses: ./.github/test-actions/test-run-shell-script/scenario
      with:
        script-base: elvish-test
        script-extension: .elv
        shell: elvish
        multiplier: 50

    - shell: bash
      run: echo "🎭 Testing script having an unknown extension..."

    - uses: ./actions/run-shell-script
      with:
        script-file: elvish-hidden.txt
        shell: elvish
        args: alpha, beta, gamma
        working-directory: ${{ github.action_path }}

    - uses: ./.github/test-actions/test-run-shell-script/expect-result
      with:
        arg-count: 3
        multiplier: 400

    - shell: bash
      run: echo "🎭 Testing inexistent optional script..."

    - shell: bash
      working-directory: ${{ github.action_path }}
      run: rm -f result.txt

    - uses: ./actions/run-shell-script
      with:
        script-file: INEXISTENT-SCRIPT
        optional: true
        working-directory: ${{ github.action_path }}

    - shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        if [[ ! -f result.txt ]]
        then
          echo "✅ Result file missing, as expected!"
        else
          echo "❌ The result file was somehow created!"
          exit 1
        fi

    - shell: bash
      run: echo "🎭 Testing optional script with unsupported, undeclared shell..."

    - shell: bash
      working-directory: ${{ github.action_path }}
      run: rm -f result.txt

    - uses: ./actions/run-shell-script
      with:
        script-file: python-test.py
        optional: true
        working-directory: ${{ github.action_path }}

    - shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        if [[ ! -f result.txt ]]
        then
          echo "✅ Result file missing, as expected!"
        else
          echo "❌ The result file was somehow created!"
          exit 1
        fi

    - shell: bash
      run: echo "🎭 Testing script with unsupported but declared shell..."

    - uses: ./actions/run-shell-script
      with:
        script-file: python-test.py
        shell: python3
        args: alpha, beta, gamma
        working-directory: ${{ github.action_path }}

    - uses: ./.github/test-actions/test-run-shell-script/expect-result
      with:
        arg-count: 3
        multiplier: 2000
