name: Install Elvish packages
description: Installs packages for the Elvish shell, supporting the extended format introduced by epm-plus.

inputs:
  packages:
    description: The comma-separated `<name>[@<version>]` packages to install.

runs:
  using: composite
  steps:
    - shell: bash
      working-directory: ${{ github.action_path }}/../../core/actions
      run: |
        use github.com/giancosta86/aurora-github/actions/install-elvish-packages
        install-elvish-packages:main'
      env:
        packages: ${{ inputs.packages }}
