name: Install Elvish packages
description: Installs packages for the Elvish shell, supporting the extended format introduced by epm-plus.

inputs:
  packages:
    description: The space-separated `<name>[@<version>]` packages to install.

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        elvish ${{ github.action_path }}/../core/actions/install-elvish-packages.elv
      env:
        packages: ${{ inputs.packages }}
