name: Test run-velvet-code
description: Tests for run-velvet-code.

runs:
  using: composite
  steps:
    - name: Setup Elvish context
      uses: ./actions/setup-elvish-context

    - shell: elvish {0}
      run: echo 🎭 Running a basic test suite...

    - shell: elvish {0}
      run: |
        echo 🐞 The pwd here is: $pwd

    - uses: ./actions/run-velvet-code
      with:
        code: |
          >> 'Basic test' {
            echo Hello, world!

            + 90 8 |
              should-be 98
          }

    - shell: elvish {0}
      run: echo 🎭 Testing a custom working-directory...

    - uses: ./actions/run-velvet-code
      with:
        working-directory: /usr/local
        code: |
          >> 'The current working directory' {
            >> 'should be the requested one' {
              put $pwd |
                should-be /usr/local
            }
          }
