name: Setup a NodeJS context
description: Installs and configures a NodeJS environment.

inputs:
  corepack-version:
    description: The version of corepack to install, empty to skip.
    default: latest

  install-dependencies:
    description: Run the package manager's `install` command.
    default: true

  working-directory:
    description: The directory containing package.json.
    default: .

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v11.0.0

    - uses: giancosta86/aurora-github/actions/install-elvish-packages@v11.0.0
      with:
        packages: github.com/giancosta86/astral-bridge@v1

    - shell: elvish {0}
      working-directory: ${{ inputs.working-directory }}
      run: |
        use github.com/giancosta86/aurora-github/actions/setup-nodejs-context
        setup-nodejs-context:main
      env:
        corepack-version: ${{ inputs.corepack-version }}
        install-dependencies: ${{ inputs.install-dependencies }}
