name: Setup a NodeJS context
description: Conditionally installs NodeJS along with pnpm, as well as the dependencies listed in package.json.

inputs:
  pnpm-colors:
    description: Enable colors for pnpm
    default: true

  project-directory:
    description: The directory containing package.json.
    default: .

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v10.3.0

    - name: Verify package.json
      shell: elvish {0}
      working-directory: ${{ inputs.project-directory }}
      run: |
        use aurora-github/nodejs/context

        echo 💻Setting up NodeJS context in "'"${{ inputs.project-directory }}"'"...
        context:check-preconditions

    - name: Detect toolchain constraints
      id: detect-nodejs-constraints
      shell: elvish {0}
      working-directory: ${{ inputs.project-directory }}
      run: |
        use aurora-github/output
        use aurora-github/nodejs/context

        output:map (context:detect-nodejs-constraints)

    - name: Install NodeJS
      if: steps.detect-nodejs-constraints.outputs.install-toolchain == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.detect-nodejs-constraints.outputs.requested-node-version }}

    - name: Print NodeJS version
      shell: elvish {0}
      working-directory: ${{ inputs.project-directory }}
      run: |
        use aurora-github/console

        console:inspect &emoji=🎡 'NodeJS version' (node --version)

    - name: Detect the requested pnpm version
      if: steps.detect-nodejs-constraints.outputs.install-toolchain == 'true'
      id: detect-pnpm-constraints
      shell: elvish {0}
      working-directory: ${{ inputs.project-directory }}
      run: |
        use aurora-github/output
        use aurora-github/nodejs/context

        output:map (context:detect-pnpm-constraints)

    - name: Install pnpm
      if: steps.detect-nodejs-constraints.outputs.install-toolchain == 'true'
      uses: pnpm/action-setup@v4
      with:
        version: ${{ steps.detect-pnpm-constraints.outputs.requested-pnpm-version }}

    - name: Setup colors for pnpm
      shell: elvish {0}
      working-directory: ${{ inputs.project-directory }}
      run: |
        use aurora-github/input
        use aurora-github/nodejs/context

        var pnpm-colors = (input:require-bool pnpm-colors '${{ inputs.pnpm-colors }}')

        context:set-pnpm-colors $pnpm-colors

    - name: Print pnpm version
      shell: elvish {0}
      working-directory: ${{ inputs.project-directory }}
      run: |
        use aurora-github/console

        console:inspect &emoji=📦 'pnpm version' (pnpm --version)

    - name: Install the dependencies
      shell: elvish {0}
      working-directory: ${{ inputs.project-directory }}
      run: |
        use aurora-github/nodejs/context

        context:install-dependencies

    - name: Print confirmation message
      shell: elvish {0}
      working-directory: ${{ inputs.project-directory }}
      run: |
        echo ✅NodeJS context in "'"${{ inputs.project-directory }}"'" ready!
