name: Setup a NodeJS context
description: Conditionally installs a specific NodeJS version, pnpm, as well as the dependencies listed in package.json.

inputs:
  project-directory:
    description: Directory containing the project files.
    default: .

runs:
  using: composite
  steps:
    - name: Print welcome message
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        echo "💻Setting up NodeJS context in '${{ inputs.project-directory }}'..."

    - name: Setup environment variables
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        if [[ ! -f "package.json" ]]
        then
          echo "❌The package.json descriptor is missing!" >&2
          exit 1
        fi

        requestedNodeVersion="$(jq -r '.engines.node // ""' package.json)"

        if [[ -n "$requestedNodeVersion" ]]
        then
          echo "🔎NodeJS version requested in package.json: $requestedNodeVersion"
          installToolchain=true
        else
          echo "💭No requested NodeJS version in package.json"
          installToolchain=false
        fi

        echo "echo 🔎Install NodeJS toolchain? $installToolchain"

        echo "requestedNodeVersion=$requestedNodeVersion" >> $GITHUB_ENV
        echo "installToolchain=$installToolchain" >> $GITHUB_ENV

    - name: Install NodeJS
      if: ${{ env.installToolchain == 'true' }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.requestedNodeVersion }}

    - name: Print NodeJS version
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        echo "🎁node version: $(node --version)"

    - name: Detect the requested pnpm version
      if: ${{ env.installToolchain == 'true' }}
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        requestedPnpmVersion="$(jq -r '.packageManager // ""' package.json | sed s/^pnpm@//)"

        echo "🔎Requested pnpm version: '$requestedPnpmVersion'"

        if [[ -n "$requestedPnpmVersion" ]]
        then
          pnpmVersion="$requestedPnpmVersion"
        else
          pnpmVersion="latest"
        fi

        echo "🔬pnpm version to install: '$pnpmVersion'"

        echo "pnpmVersion=$pnpmVersion" >> $GITHUB_ENV

    - name: Install pnpm
      if: ${{ env.installToolchain == 'true' }}
      uses: pnpm/action-setup@v4
      with:
        version: ${{ env.pnpmVersion }}

    - name: Print pnpm version
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        echo "📦pnpm version: $(pnpm --version)"

    - name: Install the dependencies
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        lockFile="pnpm-lock.yaml"

        if [[ -f "$lockFile" ]]
        then
          echo "🧊Installing dependencies with frozen lockfile, as '$lockFile' is present..."
          lockFileArg="--frozen-lockfile"
        else
          echo "🌞Installing dependencies without frozen lockfile, as '$lockFile' is missing..."
          lockFileArg="--no-frozen-lockfile"
        fi

        pnpm install $lockFileArg

        echo "✅Dependencies installed!"

    - name: Print confirmation message
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: echo "✅NodeJS context in '${{ inputs.project-directory }}' ready!"
