name: Validate Rust crate
description: Validates a Rust crate.

inputs:
  check-artifact-version:
    description: Ensures the version in Cargo.toml matches the branch name.
    required: false
    default: true

  verify-toolchain-file:
    description: Ensures 'rust-toolchain.toml' is present.
    required: false
    default: true

  project-directory:
    description: The directory containing Cargo.toml.
    required: false
    default: .

  shell:
    description: The shell used to run commands.
    required: false
    default: bash

runs:
  using: composite
  steps:
    - name: Check artifact version
      uses: giancosta86/aurora-github/actions/check-artifact-version@b2.0.0
      if: ${{ inputs.check-artifact-version == 'true' }}
      with:
        project-directory: ${{ inputs.project-directory }}
        shell: ${{ inputs.shell }}

    - name: Print Rust info
      uses: giancosta86/aurora-github/actions/print-rust-info@b2.0.0
      with:
        verify-toolchain-file: ${{ inputs.verify-toolchain-file }}
        project-directory: ${{ inputs.project-directory }}
        shell: ${{ inputs.shell }}

    - name: Check format style
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: cargo fmt --check

    - name: Lint via Clippy
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Run vanilla (no features) tests
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: cargo test

    - name: Run full (all features) tests
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: cargo test --all-features
