name: "Validate Rust crate"
description: "Validates a Rust crate"

inputs:
  project-directory:
    description: "Directory containing the Cargo.toml"
    required: false
    default: "."

  shell:
    description: "The shell used to run commands"
    required: false
    default: "bash"

runs:
  using: "composite"
  steps:
    - name: "Print Rust info"
      uses: ./actions/print-rust-info
      with:
        shell: ${{ inputs.shell }}

    #- name: Check format
    #  shell: ${{ inputs.shell }}
    #  working-directory: ${{ inputs.project-directory }}
    #  run: cargo fmt --check

    #- name: Lint via Clippy
    #  shell: ${{ inputs.shell }}
    #  working-directory: ${{ inputs.project-directory }}
    #  run: cargo clippy --all-targets --all-features -- -D warnings

    #- name: Run vanilla tests
    #  shell: ${{ inputs.shell }}
    #  working-directory: ${{ inputs.project-directory }}
    #  run: cargo test

    #- name: Run full tests
    #  shell: ${{ inputs.shell }}
    #  working-directory: ${{ inputs.project-directory }}
    #  run: cargo test --all-features
