name: Test verify-npm-package
description: Tests for verify-npm-package.

runs:
  using: composite
  steps:
    - uses: ./actions/verify-npm-package
      with:
        working-directory: tests/npm-package
