name: Test verify-npm-package

runs:
  using: composite
  steps:
    - uses: ./actions/inject-branch-version
      with:
        artifact-descriptor: ./tests/npm-package/package.json

    - uses: ./actions/verify-npm-package
      with:
        project-directory: ./tests/npm-package
