name: Test install-elvish-packages
description: Tests for install-elvish-packages

runs:
  using: composite
  steps:
    - name: Install Elvish
      shell: bash
      run: |
        source "${{ github.action_path }}/../../../actions/bootstrap.sh"

        installElvish

    - name: Setup the environment variables for the test
      shell: elvish {0}
      run: |
        use epm

        var package-path = (epm:metadata 'github.com/giancosta86/velvet')[dst]

        echo package-path=$package-path >> (get-env GITHUB_ENV)

        echo expected-tag=v3.6.0 >> (get-env GITHUB_ENV)

    - shell: elvish {0}
      run: echo 🎭 Installing the Velvet package from the main branch...

    - uses: ./actions/install-elvish-packages
      with:
        packages: github.com/giancosta86/velvet

    - shell: elvish {0}
      working-directory: ${{ env.package-path }}
      run: |
        var git-branch = (git branch --show-current)

        if (eq $git-branch main) {
          echo ✅ The package is on the main branch, as expected!
        } else {
          fail 'Current Git branch instead of main: '$git-branch
        }

    - shell: elvish {0}
      run: echo 🎭 Installing Velvet at tag ${{ env.expected-tag }}...

    - uses: ./actions/install-elvish-packages
      with:
        packages: github.com/giancosta86/velvet@${{ env.expected-tag }}

    - shell: elvish {0}
      working-directory: ${{ env.package-path }}/${{ env.expected-tag }}
      run: |
        var git-tag = (git describe --tags --always)

        var expected-tag = '${{ env.expected-tag }}'

        if (eq $git-tag $expected-tag) {
          echo ✅The package is on the $expected-tag tag, as expected!
        } else {
          fail 'Current Git tag instead of '$expected-tag': '$git-tag
        }
