name: Validate Rust web assembly
description: Validates the source files of a Rust web assembly.

inputs:
  check-artifact-version:
    description: Ensures the version in Cargo.toml matches the branch name.
    required: false
    default: true

  verify-toolchain-file:
    description: Ensures 'rust-toolchain.toml' is present.
    required: false
    default: true

  pnpm-version:
    description: The version of pnpm to use.
    required: false
    default: 9

  project-directory:
    description: The directory containing Cargo.toml.
    required: false
    default: .

  shell:
    description: The shell used to run commands
    required: false
    default: bash

runs:
  using: "composite"
  steps:
    - name: Set up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version-file: ${{ inputs.project-directory }}/client_tests/.nvmrc
        registry-url: https://registry.npmjs.org

    - name: Install wasm-pack
      uses: giancosta86/aurora-github/install-wasm-pack
      with:
        shell: ${{ inputs.shell }}

    - name: Validate Rust source files
      uses: giancosta86/aurora-github/validate-rust-crate
      with:
        check-artifact-version: ${{ inputs.check-artifact-version }}
        verify-toolchain-file: ${{ inputs.verify-toolchain-file }}
        project-directory: ${{ inputs.project-directory }}
        shell: ${{ inputs.shell }}

    - name: Run headless browser tests
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}/client_tests
      run: wasm-pack test --chrome --headless --release

    - name: Install client-side test dependencies
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}/client_tests
      run: pnpm install

    - name: Perform client-side tests
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}/client_tests
      run: pnpm test
