name: Print Rust version info
description: Print out the versions of the main Rust commands

inputs:
  project-directory:
    description: "Directory containing the Cargo.toml"
    required: false
    default: "."

  enforce-toolchain-file:
    description: Fails the workflow if the toolchain file is missing
    default: true

  shell:
    description: The shell used to run commands
    required: false
    default: bash

runs:
  using: composite
  steps:
    - name: Ensure the toolchain file is present
      if: ${{ inputs.enforce-toolchain-file == 'true' }}
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: |
        toolchain_file="rust-toolchain.toml"

        if [[ -f $toolchain_file ]]
        then
          echo "Missing toolchain file: '$toolchain_file'"
          exit 1
        fi

    - name: Print Rust command versions
      shell: ${{ inputs.shell }}
      run: |
        cargo --version
        rustc --version
        cargo fmt --version
        cargo clippy --version
