name: Print Rust version info
description: Print out the versions of the main Rust commands

inputs:
  shell:
    description: The shell used to run commands
    required: false
    default: bash

runs:
  using: composite
  steps:
    - name: Print Rust command versions
      shell: ${{ inputs.shell }}
      run: |
        cargo --version
        rustc --version
        cargo fmt --version
        cargo clippy --version
