name: "Tag and draft"
description: "Turns a branch into a Git tag, drafting a release"

inputs:
  shell:
    description: "The shell used to run commands"
    required: false
    default: "bash"

runs:
  using: "composite"
  steps:
    - name: Extract version from branch
      id: detect-version
      shell: ${{ inputs.shell }}
      run: |
        branch_name="$(git rev-parse --abbrev-ref HEAD)"
        version="$(echo "$branch_name" | sed 's/^b//')"
        echo "::set-output name=version::$version"

    - name: Print version
      shell: ${{ inputs.shell }}
      run: |
        echo "Detected version: '${{ steps.detect-version.outputs.version }}'"

    #- name: Create tag and delete branch
    #  shell: ${{ inputs.shell }}
    #  run: |
    #    git tag "v${{ steps.detect-version.outputs.version }}"

    - name: Create release draft
      shell: ${{ inputs.shell }}
      run: |
        version="${{ steps.detect-version.outputs.version }}"
        repo_name="$(basename "$GITHUB_REPOSITORY")"
        source_tag="v${version}"
        release_title="$repo_name $version"
        echo "Creating release '$release_title' from tag '$source_tag'..."

    #  run: |
    #    gh release create "$source_tag" --draft --title "$release_title"
