name: "Tag and draft"
description: "Turns a branch into a Git tag, drafting a release"

inputs:
  shell:
    description: "The shell used to run commands"
    required: false
    default: "bash"

runs:
  using: "composite"
  steps:
    - name: Extract version from branch
      id: detect-version
      shell: ${{ inputs.shell }}
      run: |
        branch_name="${{ github.head_ref }}"
        version="$(echo "$branch_name" | sed 's/^b//')"
        echo "Detected version: '$version'"
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Create tag and delete branch
      id: create-tag
      shell: ${{ inputs.shell }}
      run: |
        version="${{ steps.detect-version.outputs.version }}"
        tag_name="v${version}"
        echo "Creating tag '$tag_name'..."
        echo "tag-name=$tag_name" >> $GITHUB_OUTPUT

      # git tag "v${{ steps.detect-version.outputs.version }}"

    - name: Create release draft
      shell: ${{ inputs.shell }}
      run: |
        version="${{ steps.detect-version.outputs.version }}"
        source_tag="${{ steps.create-tag.outputs.tag-name }}" 
        repo_name="$(basename "$GITHUB_REPOSITORY")"
        release_title="$repo_name $version"
        echo "Creating release '$release_title' from tag '$source_tag'..."

    #  run: |
    #    gh release create "$source_tag" --draft --title "$release_title"
