name: Test check-rust-versions

runs:
  using: composite
  steps:
    - shell: bash
      run: echo "🎭Checking project license..."

    - name: Check project license
      uses: ./actions/check-project-license
