name: Test detect-project-tech

runs:
  using: composite
  steps:
    - uses: ./actions/detect-project-tech
      id: detect-nodejs-package
      with:
        project-directory: tests/npm-package

    - name: Tech for NodeJS package should be detected
      shell: bash
      run: |
        tech="${{ steps.detect-nodejs-package.outputs.project-tech }}"

        echo "游댍Technology retrieved for 游닍NodeJS package: '$tech'"

        if [[ "$tech" == "nodejs" ]]
        then
          echo "九Tech OK for 游닍NodeJS package!"
        else
          echo "仇Incorrect project tech!" >&2
          exit 1
        fi

    - name: Artifact descriptor for NodeJS package should be detected
      shell: bash
      run: |
        artifactDescriptor="${{ steps.detect-nodejs-package.outputs.artifact-descriptor }}"

        echo "游댍Artifact descriptor retrieved for 游닍NodeJS package: '$artifactDescriptor'"

        if [[ "$artifactDescriptor" == "package.json" ]]
        then
          echo "九ㅔrtifact descriptor OK for 游닍NodeJS package!"
        else
          echo "仇Incorrect artifact descriptor!" >&2
          exit 1
        fi

    - uses: ./actions/detect-project-tech
      id: detect-rust-crate
      with:
        project-directory: tests/rust-crate

    - name: Tech for Rust crate should be detected
      shell: bash
      run: |
        tech="${{ steps.detect-rust-crate.outputs.project-tech }}"

        echo "游댍Technology retrieved for 游Rust crate: '$tech'"

        if [[ "$tech" == "rust" ]]
        then
          echo "九Tech OK for 游Rust crate!"
        else
          echo "仇Incorrect project tech!" >&2
          exit 1
        fi

    - name: Artifact descriptor for Rust crate should be detected
      shell: bash
      run: |
        artifactDescriptor="${{ steps.detect-rust-crate.outputs.artifact-descriptor }}"

        echo "游댍Artifact descriptor retrieved for 游Rust crate: '$artifactDescriptor'"

        if [[ "$artifactDescriptor" == "Cargo.toml" ]]
        then
          echo "九ㅔrtifact descriptor OK for 游Rust crate!"
        else
          echo "仇Incorrect artifact descriptor!" >&2
          exit 1
        fi

    - uses: ./actions/detect-project-tech
      id: detect-rust-wasm
      with:
        project-directory: tests/rust-wasm

    - name: Tech for Rust web assembly should be detected
      shell: bash
      run: |
        tech="${{ steps.detect-rust-wasm.outputs.project-tech }}"

        echo "游댍Technology retrieved for 游Rust 游깷web assembly: '$tech'"

        if [[ "$tech" == "rust" ]]
        then
          echo "九Tech OK for 游Rust 游깷web assembly!"
        else
          echo "仇Incorrect project tech!" >&2
          exit 1
        fi

    - name: Artifact descriptor for Rust web assembly should be detected
      shell: bash
      run: |
        artifactDescriptor="${{ steps.detect-rust-wasm.outputs.artifact-descriptor }}"

        echo "游댍Artifact descriptor retrieved for 游Rust 游깷web assembly: '$artifactDescriptor'"

        if [[ "$artifactDescriptor" == "Cargo.toml" ]]
        then
          echo "九ㅔrtifact descriptor OK for 游Rust 游깷web assembly!"
        else
          echo "仇Incorrect artifact descriptor!" >&2
          exit 1
        fi

    - uses: ./actions/detect-project-tech
      id: detect-unknown-tech
      with:
        project-directory: tests/unknown-tech

    - name: Tech for unknown technology should be an empty string
      shell: bash
      run: |
        tech="${{ steps.detect-unknown-tech.outputs.project-tech }}"

        echo "游댍Technology retrieved for 游꾸unknown stack: '$tech'"

        if [[ -z "$tech" ]]
        then
          echo "九Tech empty, as expected, for 游꾸unknown stack"
        else
          echo "仇Incorrect project tech!" >&2
          exit 1
        fi

    - name: Artifact descriptor for unknown technology should be an empty string
      shell: bash
      run: |
        artifactDescriptor="${{ steps.detect-unknown-tech.outputs.artifact-descriptor }}"

        echo "游댍Artifact descriptor retrieved for 游꾸unknown stack: '$artifactDescriptor'"

        if [[ -z "$artifactDescriptor" ]]
        then
          echo "九ㅔrtifact descriptor empty, as expected, for 游꾸unknown stack"
        else
          echo "仇Incorrect artifact descriptor!" >&2
          exit 1
        fi
