name: Publish Rust web assembly
description: Publishes a Rust web assembly to an npm registry.

inputs:
  dry-run:
    description: Run a simulated publication via --dry-run.
    default: false

  npm-token:
    description: The secret token for publishing to the registry.

  wasm-pack-version:
    description: The wasm-pack version to install.

  npm-scope:
    description: The npm package scope or "<ROOT>".

  registry-url:
    description: The URL of the npm registry.
    default: https://registry.npmjs.org

  wasm-target:
    description: The target of the 'wasm-pack build' command.
    default: web

  node-version-directory:
    description: Relative directory containing the .nvmrc file.
    default: client-tests

  project-directory:
    description: The directory containing Cargo.toml.
    default: .

  shell:
    description: The shell used to run commands.
    default: bash

runs:
  using: composite
  steps:
    - name: Validate inputs
      shell: ${{ inputs.shell }}
      run: |
        if [[ -z "${{ inputs.dry-run }}" ]]
        then
          echo "❌Missing action input: 'dry-run'!" >&2
          exit 1
        fi

        if [[ ${{ inputs.dry-run }} != 'true' && -z "${{ inputs.npm-token }}" ]]
        then
          echo "❌Missing action input: 'npm-token'!" >&2
          exit 1
        fi

        if [[ -z "${{ inputs.wasm-pack-version }}" ]]
        then
          echo "❌Missing action input: 'wasm-pack-version'!" >&2
          exit 1
        fi

        if [[ -z "${{ inputs.wasm-target }}" ]]
        then
          echo "❌Missing action input: 'wasm-target'!" >&2
          exit 1
        fi

        if [[ -z "${{ inputs.node-version-directory }}" ]]
        then
          echo "❌Missing action input: 'node-version-directory'!" >&2
          exit 1
        fi

    - name: Parse npm scope
      id: parse-npm-scope
      uses: giancosta86/aurora-github/actions/parse-npm-scope@v6.0.0
      with:
        scope: ${{ inputs.npm-scope }}

    - name: Install wasm-pack
      uses: giancosta86/aurora-github/actions/install-wasm-pack@v6.0.0
      with:
        wasm-pack-version: ${{ inputs.wasm-pack-version }}
        shell: ${{ inputs.shell }}

    - name: Generate the NodeJS package
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: |
        scope="${{ steps.parse-npm-scope.outputs.actual-scope }}"

        if [[ -z "$scope" ]]
        then
          wasm-pack build --release --target "${{ inputs.wasm-target }}"
        else
          wasm-pack build --release --target "${{ inputs.wasm-target }}" --scope "$scope"
        fi

    - name: Copy .nvmrc to the generated NodeJS package
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: cp "${{ inputs.node-version-directory }}/.nvmrc" pkg

    - name: Publish NodeJS package
      uses: giancosta86/aurora-github/actions/publish-npm-package@v6.0.0
      with:
        dry-run: ${{ inputs.dry-run }}
        npm-token: ${{ inputs.npm-token }}
        registry-url: ${{ inputs.registry-url }}
        frozen-lockfile: false
        project-directory: ${{ inputs.project-directory }}/pkg
        shell: ${{ inputs.shell }}
