name: Publish Rust web assembly
description: Publishes a Rust web assembly to the npm registry.

inputs:
  npm-token:
    description: The secret token for publishing to npm.
    required: true

  wasm-pack-version:
    description: The wasm-pack version to install.
    required: true

  npm-scope:
    description: The npm package scope (without the initial @) or empty.
    required: true

  dry-run:
    description: Run a simulated publication via --dry-run.
    required: false
    default: false

  wasm-target:
    description: The target of the 'wasm-pack build' command.
    required: false
    default: web

  node-version-directory:
    description: Relative directory containing the .nvmrc file.
    required: false
    default: client-tests

  project-directory:
    description: The directory containing Cargo.toml.
    required: false
    default: .

  shell:
    description: The shell used to run commands.
    required: false
    default: bash

runs:
  using: composite
  steps:
    - name: Install wasm-pack
      uses: giancosta86/aurora-github/actions/install-wasm-pack@v2.0.0
      with:
        wasm-pack-version: ${{ inputs.wasm-pack-version }}
        shell: ${{ inputs.shell }}

    - name: Generate the NodeJS package
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: |
        scope="${{ inputs.npm-scope }}"

        if [[ ! -z "$scope" ]]
        then
          wasm-pack build --release --target "${{ inputs.wasm-target }}" --scope "${{ inputs.npm-scope }}"
        else
          wasm-pack build --release --target "${{ inputs.wasm-target }}"
        fi

    - name: Copy .nvmrc to the generated NodeJS package
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: cp "${{ inputs.node-version-directory }}/.nvmrc" pkg

    - name: Publish NodeJS package
      uses: giancosta86/aurora-github/actions/publish-npm-package@v2.0.0
      with:
        frozen-lockfile: false
        npm-token: ${{ inputs.npm-token }}
        dry-run: ${{ inputs.dry-run }}
        project-directory: ${{ inputs.project-directory }}/pkg
        shell: ${{ inputs.shell }}
