name: Publish Rust web assembly
description: Publishes a Rust web assembly to the npm registry.

inputs:
  npm-scope:
    description: The npm package scope (without the initial @) - or empty.
    required: true

  npm-token:
    description: The secret token for publishing to npm.
    required: true

  wasm-target:
    description: The target of the 'wasm-pack build' command.
    required: false
    default: web

  dry-run:
    description: Run a simulated publication via --dry-run.
    required: false
    default: false

  node-version-directory:
    description: The relative directory containing the .nvmrc file.
    required: false
    default: client-tests

  project-directory:
    description: The directory containing Cargo.toml.
    required: false
    default: .

  shell:
    description: The shell used to run commands.
    required: false
    default: bash

runs:
  using: composite
  steps:
    - name: Install wasm-pack
      uses: giancosta86/aurora-github/install-wasm-pack@b2.0.0

    - name: Generate the NodeJS package
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: wasm-pack build --scope "${{ inputs.npm-scope }}" --release --target "${{ inputs.wasm-target }}"

    - name: Copy .nvmrc to the generated NodeJS package
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: cp "${{ inputs.node-version-directory }}/.nvmrc" pkg

    - name: Publish NodeJS package
      uses: giancosta86/aurora-github/publish-npm-package
      with:
        frozen-lockfile: false
        npm-token: ${{ inputs.npm-token }}
        dry-run: ${{ inputs.dry-run }}
        project-directory: ${{ inputs.project-directory }}/pkg
        shell: ${{ inputs.shell }}
