name: Install system packages
description: Installs software using the platform's package manager.

inputs:
  required-command:
    description: When declared, the packages are installed only if the command is missing.

  packages:
    description: The packages to install, separated by commas.

  initial-update:
    description: Update the package list before the first installation.
    default: true

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v10.3.0

    - shell: elvish {0}
      run: |
        use aurora-github/ci-cd/input
        use aurora-github/system-packages

        system-packages:install [
          &packages=(input:list '${{ inputs.packages }}')

          &required-command=(input:string &optional required-command '${{ inputs.required-command }}')

          &initial-update=(input:bool initial-update '${{ inputs.initial-update}}')
        ]
