name: Install system packages
description: Installs software using the platform's package manager.

inputs:
  required-command:
    description: The packages will be installed only if the command is missing.

  packages:
    description: Packages to install, separated by commas.

  initial-update:
    description: Update the package list before the first installation.
    default: true

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/init-aurora-github@v11.0.2

    - shell: elvish {0}
      run: |
        use github.com/giancosta86/aurora-github/actions/install-system-packages
        install-system-packages:main
      env:
        required-command: ${{ inputs.required-command }}
        packages: ${{ inputs.packages }}
        initial-update: ${{ inputs.initial-update }}
