name: Setup an Elvish context
description: Installs the Elvish shell and a set of core libraries.

inputs:
  version:
    description: The Elvish version to install.
    default: 0.21.0

  ethereal-version:
    description: The Ethereal version to install - or empty string to skip.
    default: v1

runs:
  using: composite
  steps:
    - name: Install Elvish
      shell: bash
      run: |
        if commandExists elvish
        then
          installElvish '${{ inputs.version }}'
        else
          echo "🌟 Elvish already installed!"
        fi

    - name: Link the aurora-github core as an Elvish package
      shell: elvish {0}
      run: |
        use epm
        use os
        use path

        var link-path = (
          path:join $epm:managed-dir github.com giancosta86 aurora-github
        )

        if (not (os:exists $link-path)) {
          os:mkdir-all $epm:managed-dir

          var aurora-github-core-directory = (
            path:join '${{ github.action_path }}' .. .. core
          )

          os:symlink $aurora-github-core-directory $link-path
        }

    - name: Install Ethereal
      if: inputs.ethereal-version != ''
      uses: giancosta86/aurora-github/actions/install-elvish-packages@v11.0.0
      with:
        packages: github.com/giancosta86/ethereal@${{ inputs.ethereal-version }}
