name: Validate npm package
description: Validates the source files of a NodeJS package.

inputs:
  frozen-lockfile:
    description: Fails if 'pnpm-lock.yaml' is missing or outdated.
    required: false
    default: true

  check-artifact-version:
    description: Ensures the version in package.json matches the branch name.
    required: false
    default: true

  project-directory:
    description: The directory containing package.json.
    required: false
    default: .

  shell:
    description: The shell used to run commands.
    required: false
    default: bash

runs:
  using: composite
  steps:
    - name: Check artifact version
      uses: giancosta86/aurora-github/actions/check-artifact-version@b2.0.0
      if: ${{ inputs.check-artifact-version == 'true' }}
      with:
        project-directory: ${{ inputs.project-directory }}
        shell: ${{ inputs.shell }}

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.project-directory }}/.nvmrc
        cache: pnpm
        cache-dependency-path: ${{ inputs.project-directory }}/pnpm-lock.yaml

    - name: Install dependencies
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: |
        frozenLockfile="${{ inputs.frozen-lockfile }}"

        if [[ $frozenLockfile == "true" ]]
        then
          pnpm install --frozen-lockfile
        else
          pnpm install --no-frozen-lockfile
        fi

    - name: Create the package
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: pnpm validate
