name: Test setup-nodejs-context

runs:
  using: composite
  steps:
    - name: Backup package.json and initialize environment variables
      shell: bash
      working-directory: tests/npm-package
      run: |
        cp package.json package.json.bak

        expectedPnpmVersion="$(jq -r '.packageManager' package.json | sed s/^pnpm@//)"
        echo "🔎 Expected pnpm version: '$expectedPnpmVersion'"

        echo "expectedPnpmVersion=$expectedPnpmVersion" >> $GITHUB_ENV
        echo "dependenciesDirectory=node_modules" >> $GITHUB_ENV

    - name: The expected pnpm version should not be running
      shell: bash
      working-directory: tests/npm-package
      run: |
        if type pnpm &> /dev/null
        then
          installedPnpmVersion="$(pnpm --version)"
          echo "🔎 Pre-installed pnpm version: '$installedPnpmVersion'"

          if [[ "$installedPnpmVersion" != "$expectedPnpmVersion" ]]
          then
            echo "✅ The expected pnpm version is not running!"
          else
            echo "❌ The expected pnpm version is running! This test would be pointless!" >&2
            exit 1
          fi
        else
          echo "✅ pnpm not installed..."
        fi

    - name: Ensure the dependencies are not installed
      shell: bash
      working-directory: tests/npm-package
      run: rm -rf "$dependenciesDirectory"

    - name: Setup NodeJS from .nvmrc
      uses: ./.github/test-actions/test-setup-nodejs-context/scenario
      with:
        version-source: nvmrc

    - name: Setup NodeJS from package.json
      uses: ./.github/test-actions/test-setup-nodejs-context/scenario
      with:
        version-source: package-json

    - name: The expected pnpm version should have been installed
      shell: bash
      working-directory: tests/npm-package
      run: |
        installedPnpmVersion="$(pnpm --version)"
        echo "🔎 Installed pnpm version: '$installedPnpmVersion'"

        if [[ "$installedPnpmVersion" == "$expectedPnpmVersion" ]]
        then
          echo "✅ The expected pnpm version is being used!"
        else
          echo "❌ The expected pnpm version is not running!" >&2
          exit 1
        fi

    - name: The dependencies should have been installed
      shell: bash
      working-directory: tests/npm-package
      run: |
        if [[ -d "$dependenciesDirectory" ]]
        then
          echo "✅ The dependencies have been installed!"
        else
          echo "❌ The dependencies have not been installed!" >&2
          exit 1
        fi
