name: Test setup-nodejs-context
description: Tests for setup-nodejs-context.

runs:
  using: composite
  steps:
    - uses: ./actions/setup-elvish-context

    - shell: elvish {0}
      run: echo 🎭 Testing NodeJS context setup...

    - name: Initialize environment variables
      shell: elvish {0}
      working-directory: tests/npm-package
      run: |
        use str
        use github.com/giancosta86/aurora-github/ci-cd/env

        env:write expected-node-version (
          from-json < package.json |
            put (all)[engines][node]
        )

        env:write expected-pnpm-version (
          from-json < package.json |
            put (all)[packageManager] |
            str:split @ (all) |
            drop 1
        )

    - name: Testing preconditions
      uses: ./actions/run-velvet-code
      with:
        working-directory: tests/npm-package
        code: |
          >> 'The expected NodeJS version' {
            >> 'should not be already installed' {
              if (has-external node) {
                node --version |
                  should-not-match-regex '\bv?'(get-env expected-node-version)'\b'
              }
            }
          }

          >> 'The expected pnpm version' {
            >> 'should not be already installed' {
              if (has-external pnpm) {
                pnpm --version |
                  should-not-match-regex '\bv?'(get-env expected-pnpm-version)'\b'
              }
            }
          }

    - uses: ./actions/setup-nodejs-context
      with:
        working-directory: tests/npm-package

    - name: Testing effects
      uses: ./actions/run-velvet-code
      with:
        working-directory: tests/npm-package
        code: |
          >> 'The expected NodeJS version' {
            >> 'should now be available' {
              node --version |
                should-match-regex '\bv?'(get-env expected-node-version)'\b'
            }
          }

          >> 'The expected pnpm version' {
            >> 'should now be available' {
              pnpm --version |
                should-match-regex '\bv?'(get-env expected-pnpm-version)'\b'
            }
          }

    - shell: elvish {0}
      run: echo ✅ All tests OK!
