name: Publish to crates.io
description: Publishes a Rust crate to crates.io, with all of its features enabled.

inputs:
  dry-run:
    description: Run a simulated publication via --dry-run.
    default: false

  cargo-token:
    description: The secret token for publishing to crates.io.

  document-all-features:
    description: Enable Rustdoc for all features.
    default: true

  project-directory:
    description: The directory containing Cargo.toml.
    default: .

  shell:
    description: The shell used to run commands.
    default: bash

runs:
  using: composite
  steps:
    - name: Validate inputs
      shell: ${{ inputs.shell }}
      run: |
        if [[ -z "${{ inputs.dry-run }}" ]]
        then
          echo "❌Missing action input: 'dry-run'!" >&2
          exit 1
        fi

        if [[ ${{ inputs.dry-run }} != 'true' && -z "${{ inputs.cargo-token }}" ]]
        then
          echo "❌Missing action input: 'cargo-token'!" >&2
          exit 1
        fi

        if [[ -z "${{ inputs.document-all-features }}" ]]
        then
          echo "❌Missing action input: 'document-all-features'!" >&2
          exit 1
        fi

    - name: Enable Rustdoc for all features
      if: ${{ inputs.document-all-features == 'true' }}
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: |
        cat << EOF >> Cargo.toml

        [package.metadata.docs.rs]
        all-features = true
        EOF

    - name: Display the artifact descriptor
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: |
        echo "The content of your 🦀Cargo.toml just before publication is:"
        cat Cargo.toml

    - name: Publish to crates.io
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: |
        dryRun="${{ inputs.dry-run }}"

        if [[ "$dryRun" == "true" ]]
        then
          cargo publish --all-features --allow-dirty --dry-run
        else
          cargo publish --all-features --allow-dirty
        fi
      env:
        CARGO_REGISTRY_TOKEN: ${{ inputs.cargo-token }}
