name: Publish to crates.io
description: Publishes a Rust crate to crates.io, with all of its features enabled.

inputs:
  cargo-token:
    description: The secret token for publishing to crates.io.
    required: true

  dry-run:
    description: Run a simulated publication via --dry-run.
    required: false
    default: false

  document-all-features:
    description: Enable Rustdoc for all features.
    required: false
    default: true

  project-directory:
    description: The directory containing Cargo.toml.
    required: false
    default: .

  shell:
    description: The shell used to run commands.
    required: false
    default: bash

runs:
  using: composite
  steps:
    - name: Enable Rustdoc for all features
      if: ${{ inputs.document-all-features == 'true' }}
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: |
        cat << EOF >> Cargo.toml

        [package.metadata.docs.rs]
        all-features = true
        EOF

    - name: Display the artifact descriptor
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: |
        echo "The content of your 🦀Cargo.toml just before publication is:"
        cat Cargo.toml

    - name: Publish to crates.io
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: |
        dryRun="${{ inputs.dry-run }}"

        if [[ "$dryRun" == "true" ]]
        then
          cargo publish --all-features --allow-dirty --dry-run
        else
          cargo publish --all-features --allow-dirty
        fi
      env:
        CARGO_REGISTRY_TOKEN: ${{ inputs.cargo-token }}
