name: Publish to crates.io
description: Publishes a Rust crate to crates.io, with all the features enabled.

inputs:
  cargo-token:
    description: The secret token for publishing to crates.io.
    required: true

  dry-run:
    description: Run a simulated publication via --dry-run.
    required: false
    default: false

  project-directory:
    description: The directory containing Cargo.toml.
    required: false
    default: .

  shell:
    description: The shell used to run commands.
    required: false
    default: bash

runs:
  using: composite
  steps:
    - name: Publish to crates.io
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: |
        dryRun="${{ inputs.dry-run }}"

        if [[ $dryRun == "true" ]]
        then
          cargo publish --all-features --dry-run
        else
          cargo publish --all-features
        fi

      env:
        CARGO_REGISTRY_TOKEN: ${{ inputs.cargo-token }}
