name: Ensure that result.txt contains the expected value

inputs:
  multiplier:
    description: The factor by which the tested script multiplies the number of arguments.

  arg-count:
    description: The number of arguments that were passed to the tested script.

runs:
  using: composite
  steps:
    - name: Ensure the expected result was printed out to the result file
      shell: bash
      working-directory: ${{ github.action_path }}/..
      run: |
        expected=$((${{ inputs.arg-count }} * ${{ inputs.multiplier }}))

        scriptResult="$(cat result.txt)"

        if [[ "$scriptResult" == "$expected" ]]
        then
          echo "✅ The script result was $expected, just as expected!"
        else
          echo "❌ The script result is $scriptResult, but $expected was expected!" >&2
          exit 1
        fi
