name: scenario
description: Runs a scenario for publish-rust-crate.

inputs:
  header:
    description: The header for this test.

  pre-existing-addendum:
    description: Whether the documentation addendum should exist before running the action.

  document-all-features:
    description: Forwarded to the action.

  should-contain-addendum:
    description: Whether Cargo.toml should contain the documentation addendum.

runs:
  using: composite
  steps:
    - shell: elvish {0}
      run: echo 🎭 ${{ inputs.header }}

    - name: Restore Cargo.toml from the initial backup
      shell: elvish {0}
      working-directory: tests/rust-crate
      run: cp Cargo.toml.bak Cargo.toml

    - name: Manually add the documentation addendum
      if: inputs.pre-existing-addendum == 'true'
      shell: elvish {0}
      working-directory: tests/rust-crate
      run: |
        {
          echo
          echo '# Manually added'
          echo '[package.metadata.docs.rs]'
          echo 'all-features = true'
        } >> Cargo.toml

    - uses: ./actions/publish-rust-crate
      with:
        dry-run: true
        document-all-features: ${{ inputs.document-all-features }}
        working-directory: tests/rust-crate

    - if: inputs.should-contain-addendum == 'true'
      uses: ./actions/run-velvet-code
      with:
        working-directory: tests/rust-crate
        code: |
          >> 'Cargo.toml' {
            >> 'should contain the document-all addendum' {
              slurp < Cargo.toml |
                should-contain package.metadata.docs.rs
            }
          }

    - if: inputs.should-contain-addendum != 'true'
      uses: ./actions/run-velvet-code
      with:
        working-directory: tests/rust-crate
        code: |
          >> 'Cargo.toml' {
            >> 'should not contain the document-all addendum' {
              slurp < Cargo.toml |
                should-not-contain package.metadata.docs.rs
            }
          }
