name: Run custom tests
description: Executes arbitrary tests within a given directory; it runs a shell script by default, but can also run pnpm (for NodeJS) or cargo (for Rust).

inputs:
  optional:
    description: Exit with no error if the tests cannot be run.
    default: false

  script-file:
    description: Relative path to the script file.

  script-shell:
    description: The shell used to run script-file.

  root-directory:
    description: The directory containing the tests.

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v10.3.0

    - name: Detect the test strategy
      shell: elvish {0}
      run: |
        use aurora-github/input
        use aurora-github/custom-tests

        var inputs = [
          &root-directory=(input:require root-directory '${{ inputs.root-directory }}')
          &script-file=(input:optional '${{ inputs.script-file }}')
          &optional=(input:require-bool optional '${{ inputs.optional }}')
        ]

        custom-tests:detect-strategy $inputs

    - name: Run script
      if: env.strategy == 'script'
      shell: elvish {0}
      working-directory: ${{ inputs.root-directory }}
      run: |
        use aurora-github/script
        use aurora-github/input

        var script-file = (get-env scriptFile)
        var script-shell = (input:optional '${{ inputs.script-shell }}')

        script:run &shell=$script-shell $script-file

    - name: Setup NodeJS context
      if: env.strategy == 'nodejs'
      uses: giancosta86/aurora-github/actions/setup-nodejs-context@v10.3.0
      with:
        project-directory: ${{ inputs.root-directory }}

    - name: Run the 'verify' script from package.json
      if: env.strategy == 'nodejs'
      shell: elvish {0}
      working-directory: ${{ inputs.root-directory }}
      run: |
        echo 📦Now running the 'verify' script from package.json...
        pnpm verify

    - name: Setup Rust context
      if: env.strategy == 'rust'
      uses: giancosta86/aurora-github/actions/setup-rust-context@v10.3.0
      with:
        check-toolchain-file: false
        project-directory: ${{ inputs.root-directory }}

    - name: Run the tests via Cargo
      if: env.strategy == 'rust'
      shell: elvish {0}
      working-directory: ${{ inputs.root-directory }}
      run: |
        echo 🦀Running Rust tests with all the features enabled...
        cargo test --all-features

    - name: Print confirmation message
      if: env.strategy != 'exit'
      shell: elvish {0}
      run: echo ✅Custom tests in directory "'"${{ inputs.root-directory }}"'" run successfully!
