name: Test install-wasm-pack

runs:
  using: composite
  steps:
    - uses: ./actions/install-wasm-pack
      with:
        wasm-pack-version: 0.13.0

    - name: Verify wasm-pack
      shell: bash
      run: |
        if ! which wasm-pack
        then
          echo "❌wasm-pack not installed!" >&2
          exit 1
        fi
