name: Extract Rust code snippets
description: Extracts Rust code snippets from a Markdown file to standalone test files.

inputs:
  markdown-file:
    description: Relative path of the Markdown file containing the snippets.
    default: README.md

  optional:
    description: Just do nothing if `mardown-file` does not exist.
    default: false

  test-filename-prefix:
    description: Relative path prefix for each generated test source file.
    default: tests/readme_test_

  project-directory:
    description: The directory containing Cargo.toml.
    default: .

runs:
  using: composite
  steps:
    - name: Setup Python context
      shell: bash
      run: |
        pythonPath="${{ github.action_path }}/../../core/python"
        echo "PYTHONPATH=$pythonPath" >> $GITHUB_ENV

        echo "INPUT_MARKDOWN_FILE=${{ inputs.markdown-file }}" >> $GITHUB_ENV
        echo "INPUT_OPTIONAL=${{ inputs.optional }}" >> $GITHUB_ENV
        echo "INPUT_TEST_FILENAME_PREFIX=${{ inputs.test-filename-prefix }}" >> $GITHUB_ENV
        echo "INPUT_PROJECT_DIRECTORY=${{ inputs.project-directory }}" >> $GITHUB_ENV

    - name: Call the Python implementation
      shell: python
      run: |
        from core.extract_rust_snippets import extract_rust_snippets, Inputs

        inputs = Inputs.from_env()

        extract_rust_snippets(inputs)
