name: Extract Rust code snippets
description: Extracts Rust code snippets from a Markdown file to standalone test files.

inputs:
  markdown-file:
    description: Relative path of the Markdown file containing the snippets.
    default: README.md

  optional:
    description: Just do nothing if `mardown-file` does not exist.
    default: false

  test-filename-prefix:
    description: Relative path prefix for each generated test source file.
    default: tests/readme_test_

  project-directory:
    description: The directory containing Cargo.toml.
    default: .

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v10.3.0

    - shell: elvish {0}
      working-directory: ${{ inputs.project-directory }}
      run: |
        use aurora-github/rust-snippets

        rust-snippets:extract [
          &markdown-path='${{ inputs.markdown-file }}'
          &optional='${{ inputs.optional }}'
          &test-filename-prefix='${{ inputs.test-filename-prefix }}'
        ]
