name: Test upload-release-assets

runs:
  using: composite
  steps:
    - name: Setup environment variables
      shell: bash
      run: |
        echo "tag=test-release" >> $GITHUB_ENV

    - name: Ensure a draft release for testing exists
      shell: bash
      run: |
        echo "📝Now creating a '$tag' tag just for the tests..."
        git tag "$tag"
        git push origin "$tag"
        echo "✅Test tags created!"

        echo "📝Now creating a '$tag' draft release just for the tests..."
        gh release create "$tag" --draft --title "Test release" --notes "This version is used by the tests!"
        echo "✅Test release created!"
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Upload assets
      uses: ./actions/upload-release-assets
      with:
        release-tag: ${{ env.tag }}
        source-directory: website/static
        files: index.html

    - name: Upload multiple assets, also using quotes
      uses: ./actions/upload-release-assets
      with:
        release-tag: ${{ env.tag }}
        source-directory: website/nextjs/public
        files: next.svg 'favicon.png'

    - name: Re-upload the same asset
      uses: ./actions/upload-release-assets
      with:
        release-tag: ${{ env.tag }}
        source-directory: website/nextjs/public
        files: favicon.png
        overwrite: true

    - name: Delete the test release
      shell: bash
      run: |
        echo "🚮Now deleting the '$tag' test release and its tag..."
        gh release delete --cleanup-tag --yes "$tag"
        echo "✅Test release and tag deleted!"
      env:
        GH_TOKEN: ${{ github.token }}
