name: Test upload-release-assets
description: Tests for upload-release-assets.

runs:
  using: composite
  steps:
    - uses: giancosta86/gauntlet/actions/setup-elvish-action@v1

    - shell: bash
      working-directory: ${{ github.action_path }}
      run: elvish setup.elv
      env:
        GH_TOKEN: ${{ github.token }}

    - shell: elvish {0}
      run: echo 🎭 Uploading a single asset...

    - uses: ./actions/upload-release-assets
      with:
        release-tag: ${{ env.test-tag }}
        working-directory: website/static
        files: index.html

    - shell: elvish {0}
      run: echo 🎭 Uploading multiple assets...

    - uses: ./actions/upload-release-assets
      with:
        release-tag: ${{ env.test-tag }}
        working-directory: website/nodejs/src/assets
        files: react.svg, vite.svg

    - shell: elvish {0}
      run: echo 🎭 Re-uploading one of the previous assets...

    - uses: ./actions/upload-release-assets
      with:
        release-tag: ${{ env.test-tag }}
        working-directory: website/nodejs/src/assets
        files: vite.svg
        overwrite: true

    - shell: elvish {0}
      run: echo 🎭 Checking the artifact validity...

    - uses: ./actions/run-elvish-tests
      with:
        working-directory: ${{ github.action_path }}
        velvet-scripts: action
      env:
        GH_TOKEN: ${{ github.token }}

    - shell: bash
      working-directory: ${{ github.action_path }}
      run: elvish teardown.elv
      env:
        GH_TOKEN: ${{ github.token }}
