name: Test inject-subpath-exports

runs:
  using: composite
  steps:
    - name: Setup environment variables
      shell: bash
      working-directory: tests/npm-package
      run: |
        rootIndexFile="src/index.ts"
        echo "rootIndexFile=$rootIndexFile" >> $GITHUB_ENV

    - name: Backup package descriptor
      shell: bash
      working-directory: tests/npm-package
      run: cp package.json package.json.original

    - name: Ensure the root index file is initially missing
      shell: bash
      working-directory: tests/npm-package
      run: rm -f "$rootIndexFile"

    - shell: bash
      run: echo "🎭Run with prefer-index mode - when the root index file is missing..."

    - uses: ./actions/inject-subpath-exports
      with:
        project-directory: tests/npm-package
        mode: prefer-index

    - name: A subpath export should be generated for each subdirectory
      shell: bash
      working-directory: tests/npm-package
      run: |
        echo "🔎Asserting injected subpath exports from subdirectories only..."
        grep -q '"./alpha"' package.json
        grep -q '"./beta"' package.json
        grep -q '"./omega"' package.json

        [[ "$(jq -r '.exports."./alpha".types' package.json)" == "./dist/alpha/index.d.ts" ]] || exit 1

        [[ "$(jq -r '.exports."./alpha".import' package.json)" == "./dist/alpha/index.js" ]] || exit 1

        ! grep -q '"."' package.json
        ! grep -q '"./sigma"' package.json
        echo "✅OK!"

    - name: Restore package.json and add a root index file
      shell: bash
      working-directory: tests/npm-package
      run: |
        cp package.json.original package.json
        touch "$rootIndexFile"

    - shell: bash
      run: echo "🎭Run again with prefer-index mode - now that the root index exists..."

    - uses: ./actions/inject-subpath-exports
      with:
        project-directory: tests/npm-package
        mode: prefer-index

    - name: A subpath export should be generated only for the root index
      shell: bash
      working-directory: tests/npm-package
      run: |
        echo "🔎Asserting injected subpath export for root index only..."
        ! grep -q '"./alpha"' package.json
        ! grep -q '"./beta"' package.json
        ! grep -q '"./omega"' package.json
        grep -q '"."' package.json

        [[ "$(jq -r '.exports.".".types' package.json)" == "./dist/index.d.ts" ]] || exit 1

        [[ "$(jq -r '.exports.".".import' package.json)" == "./dist/index.js" ]] || exit 1

        ! grep -q '"./sigma"' package.json
        echo "✅OK!"

    - name: Restore package descriptor with custom export
      shell: bash
      working-directory: tests/npm-package
      run: |
        cp package.json.original package.json

        jq '.exports += {"./my-export": {"types": "./dist/my-export/index.d.ts", "import": "./dist/my-export/index.js"}}' package.json > package.json.temp

        mv package.json.temp package.json

    - shell: bash
      run: echo "🎭Run action with 'all' mode..."

    - uses: ./actions/inject-subpath-exports
      with:
        project-directory: tests/npm-package
        mode: all

    - name: Subpath exports should be generated for both root index and subdirectories
      shell: bash
      working-directory: tests/npm-package
      run: |
        echo "🔎Asserting that all exports exist, including the manual ones..."
        grep -q '"./my-export"' package.json
        grep -q '"./alpha"' package.json
        grep -q '"./beta"' package.json
        grep -q '"./omega"' package.json
        grep -q '"."' package.json
        ! grep -q '"./sigma"' package.json
        echo "✅OK!"
