name: Publish JVM project
description: Publishes a project for the Java Virtual Machine - using Maven or Gradle.

inputs:
  dry-run:
    description: Run a simulated publication.
    default: false

  auth-user:
    description: Username for publishing.

  auth-token:
    description: Secret token for publishing.

  quiet-tool:
    description: Run the build tool in quiet mode
    default: true

  working-directory:
    description: Directory containing the project descriptor.
    default: .

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/init-aurora-github@v12.0.1

    - uses: giancosta86/aurora-github/actions/inject-branch-version@v12.0.1
      with:
        files: pom.xml build.gradle{'' .kts}
        working-directory: ${{ inputs.working-directory }}

    - shell: elvish {0}
      working-directory: ${{ inputs.working-directory }}
      run: |
        use github.com/giancosta86/aurora-github/actions/setup-jvm-context
        setup-jvm-context:main

    - shell: elvish {0}
      working-directory: ${{ inputs.working-directory }}
      run: |
        use github.com/giancosta86/aurora-github/actions/publish-jvm-project
        publish-jvm-project:main
      env:
        dry-run: ${{ inputs.dry-run }}
        quiet-tool: ${{ inputs.quiet-tool }}
        JVM_AUTH_USER: ${{ inputs.auth-user }}
        JVM_AUTH_TOKEN: ${{ inputs.auth-token }}

    - shell: elvish {0}
      run: echo ✅☕ JVM publication action successful!
