name: Publish JVM project
description: Publishes a project for the Java Virtual Machine - using Maven or Gradle.

inputs:
  dry-run:
    description: Run a simulated publication.
    default: false

  auth-user:
    description: The username for publishing.

  auth-token:
    description: The secret token for publishing.

  java-version:
    description: Java version (in SDKMAN) to install.

  tool-version:
    description: Build tool version (in SDKMAN) to install.

  quiet-tool:
    description: Run the build tool in quiet mode
    default: true

  website-directory:
    description: Relative directory containing the project website.
    default: website

  enforce-branch-version:
    description: How the branch version should be enforced.
    default: inject

  project-directory:
    description: The directory containing the project descriptor.
    default: .

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v10.3.0

    - name: Validate inputs
      shell: elvish {0}
      working-directory: ${{ inputs.project-directory }}
      run: |
        use aurora-github/input

        input:require-bool dry-run '${{ inputs.dry-run }}'

        input:require-bool quiet-tool '${{ inputs.quiet-tool }}'

        input:require website-directory '${{ inputs.website-directory }}'

        input:require enforce-branch-version '${{ inputs.enforce-branch-version }}'

    - name: Enforce branch version
      uses: giancosta86/aurora-github/actions/enforce-branch-version@v10.3.0
      with:
        mode: ${{ inputs.enforce-branch-version }}
        project-directory: ${{ inputs.project-directory }}

    - name: Detect the build tool
      shell: elvish {0}
      run: |
        use path
        use aurora-github/env
        use aurora-github/console
        use aurora-github/jvm/project

        var project = (project:detect '${{ inputs.project-directory }}')

        var build-tool = $project[build-tool]
        console:inspect &emoji=💡 'Build tool' $build-tool

        var descriptor-name = (path:base $project[descriptor-path])
        console:inspect &emoji=📃 'Descriptor name' $descriptor-name

        env:write buildTool $build-tool
        env:write descriptorName $descriptor-name

    - name: Install Java
      if: inputs.java-version != ''
      uses: giancosta86/aurora-github/actions/install-via-sdkman@v10.3.0
      with:
        candidate: java
        version: ${{ inputs.java-version }}

    - name: Install Maven
      if: env.buildTool == 'mvn' && inputs.tool-version != ''
      uses: giancosta86/aurora-github/actions/install-via-sdkman@v10.3.0
      with:
        candidate: maven
        version: ${{ inputs.tool-version }}

    - name: Install Gradle
      if: env.buildTool == 'gradle' && inputs.tool-version != ''
      uses: giancosta86/aurora-github/actions/install-via-sdkman@v10.3.0
      with:
        candidate: gradle
        version: ${{ inputs.tool-version }}

    - name: Prepare Maven settings
      if: env.buildTool == 'mvn'
      shell: elvish {0}
      working-directory: ${{ inputs.project-directory }}
      run: |
        use aurora-github/jvm/maven/settings

        settings:enforce '${{ github.action_path }}/settings.xml'

    - name: Prepare Gradle settings
      if: env.buildTool == 'gradle'
      shell: elvish {0}
      working-directory: ${{ inputs.project-directory }}
      run: |
        use aurora-github/jvm/gradle/settings

        settings:check (get-env descriptorName)

    - name: Publish the GitHub Pages website
      uses: giancosta86/aurora-github/actions/publish-github-pages@v10.3.0
      with:
        optional: true
        source-directory: ${{ inputs.project-directory }}/${{ inputs.website-directory }}
        dry-run: ${{ inputs.dry-run }}
        enforce-branch-version: ${{ inputs.enforce-branch-version }}

    - name: Publish via Maven
      if: env.buildTool == 'mvn'
      shell: elvish {0}
      working-directory: ${{ inputs.project-directory }}
      run: |
        use aurora-github/input
        use aurora-github/jvm/maven

        var quiet = (input:require-bool quiet-tool '${{ inputs.quiet-tool }}')

        var dry-run = (input:require-bool dry-run '${{ inputs.dry-run }}')

        maven:publish &quiet=$quiet $dry-run
      env:
        JVM_AUTH_USER: ${{ inputs.auth-user }}
        JVM_AUTH_TOKEN: ${{ inputs.auth-token }}

    - name: Publish via Gradle
      if: env.buildTool == 'gradle'
      shell: elvish {0}
      working-directory: ${{ inputs.project-directory }}
      run: |
        use aurora-github/lang
        use aurora-github/input
        use aurora-github/jvm/gradle

        var quiet = (input:require-bool quiet-tool '${{ inputs.quiet-tool }}')

        var dry-run = (input:require-bool dry-run '${{ inputs.dry-run }}')

        var dry-run-arg = (lang:ternary $dry-run [--dry-run] [])

        echo 🐘Running Gradle to publish the project...

        gradle:run &quiet=$quiet $@dry-run-arg publish

        echo ✅🐘Gradle publication step successful!
      env:
        JVM_AUTH_USER: ${{ inputs.auth-user }}
        JVM_AUTH_TOKEN: ${{ inputs.auth-token }}
