name: Test extract-rust-snippets

runs:
  using: composite
  steps:
    - name: Try to generate test files from Markdown file without snippets
      uses: ./actions/extract-rust-snippets
      with:
        project-directory: tests/unknown-tech
        markdown-file: NO-SNIPPETS.md
        test-filename-prefix: fake-tests/fake-

    - name: The Rust test files should be created
      shell: bash
      working-directory: tests/unknown-tech/fake-tests
      run: |
        echo "🔎Inspecting the 'fake-tests' subdirectory..."
        ls -1 2>/dev/null

        files="$(ls -1 2>/dev/null)"

        if [[ ! -z "$files" ]]
        then
          echo "❌There should be no generated test files!" >&2
          exit 1
        fi

    - name: Generate test files from Markdown file with snippets
      uses: ./actions/extract-rust-snippets
      with:
        project-directory: tests/unknown-tech

    - name: The Rust test files should be created
      shell: bash
      working-directory: tests/unknown-tech/tests
      run: |
        echo "🔎Inspecting the 'tests' subdirectory..."
        ls -1 2>/dev/null

        echo ""

        echo "🔎Now checking the test files..."

        for i in {1..3}
        do
          testFile="readme_test_${i}.rs"
          if [[ ! -f "$testFile" ]]
          then
            echo "❌Missing Rust test file: '$testFile'"
            exit 1
          fi
        done

        echo "✅All the test files exist!"

    - name: The first test must contain the expected Rust source code
      shell: bash
      working-directory: tests/unknown-tech/tests
      run: |
        testFile="readme_test_1.rs"

        echo "🔎Inspecting the content of the first test file..."
        grep -q 'Alpha' "$testFile"
        grep -q 'Beta' "$testFile"
        grep -q 'main().unwrap();' "$testFile"
        echo "✅First test file OK!"

    - name: The second test must contain the expected Rust source code
      shell: bash
      working-directory: tests/unknown-tech/tests
      run: |
        testFile="readme_test_2.rs"

        echo "🔎Inspecting the content of the second test file..."
        grep -q 'Gamma' "$testFile"
        grep -q 'Delta' "$testFile"
        grep -q 'Epsilon' "$testFile"
        grep -q 'main().unwrap();' "$testFile"
        echo "✅Second test file OK!"

    - name: The third test must contain the expected Rust source code
      shell: bash
      working-directory: tests/unknown-tech/tests
      run: |
        testFile="readme_test_3.rs"

        echo "🔎Inspecting the content of the third test file..."
        grep -q 'Sigma' "$testFile"
        grep -q 'Tau' "$testFile"
        grep -q 'main().unwrap();' "$testFile"
        echo "✅Third test file OK!"
