name: Test publish-github-pages
description: Tests for publish-github-pages.

runs:
  using: composite
  steps:
    - uses: ./actions/setup-elvish-context

    - shell: elvish {0}
      run: echo 🎭 Testing static files...

    - uses: ./actions/publish-github-pages
      with:
        working-directory: website/static
        dry-run: false

    - shell: elvish {0}
      run: echo 🎭 Testing a Maven-generated site...

    - uses: ./actions/publish-github-pages
      with:
        working-directory: tests/maven-project
        dry-run: true

    - shell: elvish {0}
      run: echo 🎭 Testing a NodeJS site...

    - id: publish-nodejs-pages
      uses: ./actions/publish-github-pages
      with:
        working-directory: website/nodejs
        dry-run: true

    - uses: ./actions/run-velvet-code
      with:
        code: |
          >> 'The website URL' {
            >> 'should be the expected one' {
              put '${{ steps.publish-nodejs-pages.outputs.url }}' |
                should-be 'https://gianlucacosta.info/aurora-github/'
            }
          }
