name: Test publish-github-pages
description: Tests for publish-github-pages.

runs:
  using: composite
  steps:
    - shell: bash
      run: echo "🎭 Now publishing (in dry-run) static files..."

    - name: A static website should be publishable
      uses: ./actions/publish-github-pages
      with:
        working-directory: website/static
        dry-run: true

    - shell: bash
      run: echo "🎭 Now publishing (in dry-run) a Maven-generated site..."

    - name: A Maven-generated website should be publishable
      uses: ./actions/publish-github-pages
      with:
        working-directory: tests/maven-project
        dry-run: true

    - shell: bash
      run: echo "🎭 Now publishing a NextJS site..."

    - name: A NextJS website should be publishable
      id: publish-nextjs-pages
      uses: ./actions/publish-github-pages
      with:
        working-directory: website/nextjs

    - name: The URL of the website should be defined
      shell: bash
      run: |
        websiteUrl="${{ steps.publish-nextjs-pages.outputs.url }}"

        if [[ -n "$websiteUrl" ]]
        then
          echo "✅ Website published and available at: '$websiteUrl'"
        else
          echo "❌ Website not available!" >&2
          exit 1
        fi

    - shell: bash
      run: echo "🎭 Now trying to publish an inexistent source directory..."

    - uses: ./actions/publish-github-pages
      with:
        working-directory: INEXISTENT_DIRECTORY
        optional: true

    - shell: bash
      run: echo "🎭 Now trying to omit the source directory..."

    - uses: ./actions/publish-github-pages
      with:
        working-directory: ""
        optional: true
