name: Test publish-github-pages

runs:
  using: composite
  steps:
    - shell: bash
      run: echo "🎭Now publishing static files with dry-run enabled..."

    - name: A static website should be publishable
      id: publish-static-pages
      uses: ./actions/publish-github-pages
      with:
        source-directory: website/static
        dry-run: true

    - shell: bash
      run: echo "🎭Now publishing a NextJS site..."

    - name: A NextJS website should be publishable
      id: publish-nextjs-pages
      uses: ./actions/publish-github-pages
      with:
        source-directory: website/nextjs

    - name: The URL of the website should be defined
      shell: bash
      run: |
        websiteUrl="${{ steps.publish-nextjs-pages.outputs.url }}"

        if [[ -n "$websiteUrl" ]]
        then
          echo "✅Website published and available at: '$websiteUrl'"
        else
          echo "❌Website not available!" >&2
          exit 1
        fi
