name: Test publish-github-pages
description: Tests for publish-github-pages.

runs:
  using: composite
  steps:
    - uses: ./actions/init-aurora-github

    - shell: elvish {0}
      run: echo 🎭 Testing a static site...

    - uses: ./actions/publish-github-pages
      with:
        working-directory: website/static
        dry-run: true

    - shell: elvish {0}
      run: echo 🎭 Testing a Maven-generated site...

    - uses: ./actions/publish-github-pages
      with:
        working-directory: tests/maven-project
        dry-run: true

    - shell: elvish {0}
      run: echo 🎭 Testing a NodeJS site...

    - id: publish-nodejs-pages
      uses: ./actions/publish-github-pages
      with:
        working-directory: website/nodejs

    - uses: ./actions/run-elvish-tests
      with:
        working-directory: ${{ github.action_path }}
        velvet-scripts: action
      env:
        website-url: ${{ steps.publish-nodejs-pages.outputs.url }}
