name: Install SDK via SDKMAN
description: Installs the requested SDK using SDKMAN.

inputs:
  candidate:
    description: Identifier (in SDKMAN) of the SDK to install.

  version:
    description: Identifier (in SDKMAN) of the version.

runs:
  using: composite
  steps:
    - uses: giancosta86/gauntlet/actions/setup-elvish-action@v1

    - shell: elvish {0}
      run: |
        use github.com/giancosta86/aurora-github/actions/install-via-sdkman
        install-via-sdkman:main
      env:
        candidate: ${{ inputs.candidate }}
        version: ${{ inputs.version }}
