name: Install SDK via SDKMAN
description: Installs the requested SDK using SDKMAN.

inputs:
  candidate:
    description: Identifier (in SDKMAN) of the SDK to install.

  version:
    description: Identifier (in SDKMAN) of the version.

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v10.3.0

    - shell: elvish {0}
      run: |
        use github.com/giancosta86/aurora-elvish/curl
        use aurora-github/ci-cd/input
        use aurora-github/jvm/sdkman

        var candidate = (input:string candidate '${{ inputs.candidate }}')

        var version = (input:string version '${{ inputs.version }}')

        curl:disable-non-error-output

        sdkman:install-sdk $candidate $version
