name: Install SDK via SDKMAN.
description: Installs the requested SDK using SDKMAN.

inputs:
  candidate:
    description: Identifier (in SDKMAN) of the SDK to install.

  version:
    description: Identifier (in SDKMAN) of the version.

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v10.3.0

    - shell: elvish {0}
      run: |
        use aurora-github/curl
        use aurora-github/input
        use aurora-github/jvm/sdkman

        var candidate = (input:require candidate '${{ inputs.candidate }}')

        var version = (input:require version '${{ inputs.version }}')

        curl:output-errors-only

        sdkman:install-sdk $candidate $version
