name: Install SDK via SDKMAN.
description: Installs the requested SDK using SDKMAN.

inputs:
  candidate:
    description: Identifier (in SDKMAN) of the SDK to install.

  version:
    description: Identifier (in SDKMAN) of the version.

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        source "${{ github.action_path }}/action.sh"

        installViaSdkman '${{ inputs.candidate }}' '${{ inputs.version }}'
