name: Test setup-elvish-context

inputs:
  skip-if-existing:
    description: Forwarded to the action

runs:
  using: composite
  steps:
    - shell: bash
      run: echo "🎭Setup the shell with startup packages..."

    - uses: ./actions/setup-elvish-context
      with:
        packages: github.com/elves/sample-pkg, github.com/xiaq/edit.elv
        skip-if-existing: ${{ inputs.skip-if-existing }}
        quiet: false

    - shell: bash
      run: echo "🎭Run Elvish code to confirm..."

    - shell: elvish {0}
      run: |
        var message = '✅Elvish confirms: the shell is ready! 🚀'

        echo $message
