name: Test setup-elvish-context
description: Tests for setup-elvish-context

runs:
  using: composite
  steps:
    - shell: bash
      run: echo "🎭 Setting up an Elvish context with default Ethereal..."

    - uses: ./actions/setup-elvish-context

    - shell: elvish {0}
      run: |
        var message = '✅ Elvish confirms: the shell is ready! 🚀'

        echo $message

    - shell: elvish {0}
      run: |
        echo 🎭 Trying to access the aurora-github library...

        use github.com/giancosta86/aurora-github/math-test

        if (== (math-test:add 90 2) 92) {
          echo ✅ aurora-github library accessible!
        } else {
         fail 'Error while accessing the library!'
        }

    - shell: elvish {0}
      run: |
        echo 🎭 Trying to access the ethereal library...

        use github.com/giancosta86/ethereal/v1/lang

        if (== (lang:ternary $false 90 98) 98) {
          echo ✅ ethereal library accessible!
        } else {
         fail 'Error while accessing the library!'
        }

    - shell: elvish {0}
      run: echo 🎭 Setting up an Elvish context without Ethereal...

    - uses: ./actions/setup-elvish-context
      with:
        ethereal-version: ""

    - shell: elvish {0}
      run: echo ✅ All tests OK!
