name: Test publish-npm-package

runs:
  using: composite
  steps:
    - uses: ./actions/inject-branch-version
      with:
        artifact-file: ./tests/npm-package/package.json

    - uses: ./actions/publish-npm-package
      with:
        dry-run: true
        npm-token: ""
        project-directory: ./tests/npm-package
