name: Test publish-npm-package
description: Tests for publish-npm-package.

runs:
  using: composite
  steps:
    - uses: ./actions/publish-npm-package
      with:
        dry-run: true
        working-directory: tests/npm-package
