name: Test publish-npm-package

inputs:
  fake-npm-token:
    description: The fake NPM token used for publication

runs:
  using: composite
  steps:
    - uses: ./actions/publish-npm-package
      with:
        dry-run: true
        project-directory: tests/npm-package
        npm-token: ${{ inputs.fake-npm-token }}
