name: Test publish-rust-crate

runs:
  using: composite
  steps:
    - uses: ./actions/inject-branch-version
      with:
        project-directory: tests/rust-crate

    - uses: ./actions/publish-rust-crate
      with:
        dry-run: true
        project-directory: tests/rust-crate
