import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Test page for aurora-github",
  description: "Generated by NextJS",

  icons: {
    icon: "/aurora-github/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
