name: Check Rust version info
description: Displays the versions of the main Rust components, after ensuring that 'rust-toolchain.toml' is in the project directory.

inputs:
  project-directory:
    description: The directory containing the toolchain file.
    default: "."

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v10.3.0

    - shell: elvish {0}
      working-directory: ${{ inputs.project-directory }}
      run: |
        use aurora-github/rust

        rust:check-versions
