name: Check Rust version info
description: Displays the versions of the main Rust components, after ensuring that 'rust-toolchain.toml' is in the project directory.

inputs:
  project-directory:
    description: The directory containing the toolchain file.
    default: "."

runs:
  using: composite
  steps:
    - shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        main() {
          checkToolchainFile
          printToolVersions
        }

        checkToolchainFile() {
          local toolchainFile="rust-toolchain.toml"

          if [[ -f "$toolchainFile" ]]
          then
            echo "✅Toolchain file found: $toolchainFile"
          else
            echo "❌Missing toolchain file: '$toolchainFile'" >&2
            exit 1
          fi
        }

        printToolVersions() {
          echo "🦀Rust toolchain versions:"
          cargo --version
          rustc --version
          cargo fmt --version
          cargo clippy --version
          echo "🦀🦀🦀"
        }

        main