name: Check GitHub Actions references
description: Prevents cross-branch `uses:` directives between GitHub actions residing below the same root directory.

inputs:
  actions-directory:
    description: Root of the directory tree containing the actions.
    default: actions

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/init-aurora-github@v12.0.1

    - shell: elvish {0}
      working-directory: ${{ inputs.actions-directory }}
      run: |
        use github.com/giancosta86/aurora-github/actions/check-action-references
        check-action-references:main
