name: Check GitHub Actions references
description: Prevents inter-branch 'uses:' directives to GitHub actions residing below the same root directory.

inputs:
  actions-directory:
    description: The root of the directory tree containing the actions.
    default: ./actions

  shell:
    description: The shell used to run commands.
    default: bash

runs:
  using: composite
  steps:
    - name: Detect branch and version
      id: detect-branch-version
      uses: giancosta86/aurora-github/actions/detect-branch-version@v4.0.0
      with:
        shell: ${{ inputs.shell }}

    - name: Fail on inter-branch local references
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.actions-directory }}
      run: |
        branch="${{ steps.detect-branch-version.outputs.branch }}"
        fullRepo="$GITHUB_REPOSITORY"

        echo "Now in 🌲branch: '$branch'. 🧭Full repository name: '$fullRepo'."

        hasReferencesToOtherBranches=false

        while IFS= read -r referenceLine
        do
          if [[ "$referenceLine" != *@"${branch}" ]]
          then
            echo "---> $referenceLine" >&2
            hasReferencesToOtherBranches=true
          fi
        done < <(find . -name '*.yml' -print | xargs grep -Pn "uses:\s+${fullRepo}/")

        if [[ "$hasReferencesToOtherBranches" == "true" ]]
        then
          echo "❌There are references to actions within '${{ inputs.actions-directory }}' residing in other branches!" >&2
          exit 1
        else
          echo "✅No inter-branch action references detected!"
        fi
