name: Check GitHub Actions references
description: Prevents cross-branch 'uses:' directives to GitHub actions residing below the same root directory.

inputs:
  actions-directory:
    description: The root of the directory tree containing the actions.
    default: actions

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v10.3.0

    - shell: elvish {0}
      run: |
        use aurora-github/action-references

        action-references:check '${{ inputs.actions-directory }}'
