name: Check GitHub Actions references
description: Prevents cross-branch 'uses:' directives to GitHub actions residing below the same root directory.

inputs:
  actions-directory:
    description: The root of the directory tree containing the actions.
    default: actions

runs:
  using: composite
  steps:
    - name: Detect branch and version
      id: detect-branch-version
      uses: giancosta86/aurora-github/actions/detect-branch-version@v7.0.0

    - name: Fail on cross-branch local references
      shell: bash
      working-directory: ${{ inputs.actions-directory }}
      run: |
        branch="${{ steps.detect-branch-version.outputs.branch }}"
        echo "🌲Current branch: '$branch'"

        fullRepo="$GITHUB_REPOSITORY"
        echo "🧭Full repository name: '$fullRepo'"

        hasReferencesToOtherBranches=false

        while IFS= read -r referenceLine
        do
          if [[ "$referenceLine" != *@"${branch}" ]]
          then
            echo "⛔Cross-branch reference found: $referenceLine" >&2
            hasReferencesToOtherBranches=true
          fi
        done < <(find -name '*.yml' -print | xargs grep -Pn "uses:\s+${fullRepo}/")

        if [[ "$hasReferencesToOtherBranches" == "true" ]]
        then
          echo "❌There are references to actions within '${{ inputs.actions-directory }}' residing in other branches!" >&2
          exit 1
        else
          echo "✅No cross-branch action references detected!"
        fi
