name: Check project license
description: Ensures the validity of the project license file.

inputs:
  license-file:
    description: The path to the license file.
    default: LICENSE

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        licenseFile="${{ inputs.license-file }}"

        main() {
          licenseFileMustExist

          licenseMustIncludeCurrentYear
        }

        licenseFileMustExist() {
          if [[ -f "$licenseFile" ]]
          then
            echo "✅License file found: $licenseFile"
          else
            echo "❌Missing license file: '$licenseFile'" >&2
            exit 1
          fi
        }

        licenseMustIncludeCurrentYear() {
          currentYear="$(date +"%Y")"

          if [[ -z "$currentYear" ]]
          then
            echo "❌Cannot detect the current year!" >&2
            exit 1
          fi

          echo "🔎Current year: $currentYear"

          echo "🔎Searching the license file for the current year..."

          if grep --color=always "$currentYear" "$licenseFile"
          then
            echo "✅Current year found in the license file!"
          else
            echo "❌Cannot find the current year in the license file!" >&2
            exit 1
          fi
        }

        main
