name: Check project license
description: Ensures the validity of the project license file.

inputs:
  license-file:
    description: The path to the license file.
    default: LICENSE

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v10.3.0

    - shell: elvish {0}
      run: |
        use aurora-github/license-file

        license-file:check '${{ inputs.license-file }}'
