name: Check project license
description: Checks the validity of the project license file.

inputs:
  license-file:
    description: The path to the license file.
    default: LICENSE

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v11.0.0

    - shell: elvish {0}
      run: |
        use aurora-github/ci-cd/input
        use aurora-github/license-file

        var license-file = (input:file license-file '${{ inputs.license-file }}')

        license-file:check $license-file
