name: Detect project type
description: Tries to infer the current project type from its source files.

inputs:
  project-directory:
    description: The directory containing the project.
    required: false
    default: .

  shell:
    description: The shell used to run commands.
    required: false
    default: bash

outputs:
  project-tech:
    description: The project type. Can be either 'nodejs' or 'rust'.
    value: ${{ steps.detect-project-tech.outputs.project-tech }}

runs:
  using: composite
  steps:
    - name: Detect project type
      id: detect-project-tech
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.project-directory }}
      run: |
        if [[ -f "package.json" ]]
        then
          echo "📦NodeJS project type detected"
          echo "project-tech=nodejs" >> $GITHUB_OUTPUT
        elif [[ -f "Cargo.toml" ]]
        then
          echo "🦀Rust project detected"
          echo "project-tech=rust" >> $GITHUB_OUTPUT
        else
          echo "❌It's impossible to detect the project type"
          echo "project-tech=" >> $GITHUB_OUTPUT
        fi
