name: Parse npm scope
description: Parses a mandatory npm scope declaration.

inputs:
  scope:
    description: The npm scope to parse. Can be either '<ROOT>' or a string with an optional leading "@".

outputs:
  actual-scope:
    description: The scope without '@', or the empty string for root scope.
    value: ${{ steps.parse-actual-scope.outputs.actual-scope }}

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v10.3.0

    - id: parse-actual-scope
      shell: elvish {0}
      run: |
        use aurora-github/core
        use aurora-github/npm

        core:write-output actual-scope (npm:parse-scope '${{ inputs.scope }}')
