name: Parse npm scope
description: Parses a mandatory npm scope declaration.

inputs:
  scope:
    description: The npm scope to parse. Can be either '<ROOT>' or a string with an optional leading "@".

outputs:
  actual-scope:
    description: The scope without '@', or the empty string for root scope.
    value: ${{ steps.parse-actual-scope.outputs.actual-scope }}

runs:
  using: composite
  steps:
    - name: Setup Python context
      shell: bash
      run: |
        pythonPath="${{ github.action_path }}/../.."
        echo "PYTHONPATH=$pythonPath" >> $GITHUB_ENV

        echo "INPUT_SCOPE=${{ inputs.scope }}" >> $GITHUB_ENV

    - name: Call the Python implementation
      id: parse-actual-scope
      shell: python
      run: |
        from core.parse_npm_scope import parse_npm_scope, Inputs

        inputs = Inputs.from_env()

        parse_npm_scope(inputs).write_to_github_output()
