name: Parse npm scope
description: Parses a mandatory npm scope declaration.

inputs:
  scope:
    description: The npm scope to parse. Can be either '<ROOT>' or a string with an optional leading "@".

outputs:
  actual-scope:
    description: The scope without '@', or the empty string for root scope.
    value: ${{ steps.parse-actual-scope.outputs.actual-scope }}

runs:
  using: composite
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [[ -z "${{ inputs.scope }}" ]]
        then
          echo "❌Missing action input: 'scope'!" >&2
          exit 1
        fi

    - name: Parse the actual npm scope
      id: parse-actual-scope
      shell: bash
      run: |
        requestedScope="${{ inputs.scope }}"

        if [[ "$requestedScope" == "<ROOT>" ]]
        then
          actualScope=""
          echo "🫚Root npm scope detected!"
        else
          actualScope="$(echo "$requestedScope" | sed 's/^@//')"
          echo "🖌️Custom npm scope detected: '$actualScope'"
        fi

        echo "actual-scope=$actualScope" >> $GITHUB_OUTPUT
