name: Install wasm-pack
description: Installs wasm-pack, for creating Rust-based web assemblies.

inputs:
  wasm-pack-version:
    description: The wasm-pack version to install.

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v10.3.0

    - shell: elvish {0}
      run: |
        use aurora-github/core
        use aurora-github/wasm

        var version = (
          core:require-input "wasm-pack-version" ${{ inputs.wasm-pack-version }}
        )

        wasm:install-wasm-pack $version
