name: Install wasm-pack
description: Installs wasm-pack, for creating Rust-based web assemblies.

inputs:
  wasm-pack-version:
    description: The wasm-pack version to install.
    required: true

  shell:
    description: The shell used to run commands.
    required: false
    default: bash

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Install wasm-pack via pnpm
      shell: ${{ inputs.shell }}
      run: pnpm add -g "wasm-pack@${{ inputs.wasm-pack-version }}"

    - name: Print wasm-pack version
      shell: ${{ inputs.shell }}
      run: wasm-pack --version
