name: Install wasm-pack
description: Installs wasm-pack, for creating Rust-based web assemblies.

inputs:
  wasm-pack-version:
    description: The version of wasm-pack to install.

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v10.3.0

    - shell: elvish {0}
      run: |
        use aurora-github/ci-cd/input
        use aurora-github/rust/wasm-pack

        var version = (
          input:string wasm-pack-version '${{ inputs.wasm-pack-version }}'
        )

        wasm-pack:install $version
