name: Install wasm-pack
description: Installs wasm-pack, for creating Rust-based web assemblies.

inputs:
  wasm-pack-version:
    description: The wasm-pack version to install.

  shell:
    description: The shell used to run commands.
    default: bash

runs:
  using: composite
  steps:
    - name: Validate inputs
      shell: ${{ inputs.shell }}
      run: |
        if [[ -z "${{ inputs.wasm-pack-version }}" ]]
        then
          echo "❌Missing action input: 'wasm-pack-version'!" >&2
          exit 1
        fi

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Install wasm-pack via pnpm
      shell: ${{ inputs.shell }}
      run: pnpm add -g "wasm-pack@${{ inputs.wasm-pack-version }}"

    - name: Print wasm-pack version
      shell: ${{ inputs.shell }}
      run: |
        echo "🔎Now invoking wasm-pack..."
        wasm-pack --version
        echo "✅wasm-pack installed!"
