name: Install wasm-pack
description: Installs wasm-pack, for creating Rust-based web assemblies.

inputs:
  wasm-pack-version:
    description: The wasm-pack version to install.

runs:
  using: composite
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [[ -z "${{ inputs.wasm-pack-version }}" ]]
        then
          echo "❌Missing action input: 'wasm-pack-version'!" >&2
          exit 1
        fi

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Install wasm-pack via pnpm
      shell: bash
      run: |
        echo "🌐Installing wasm-pack ${{ inputs.wasm-pack-version }}..."
        pnpm add -g "wasm-pack@${{ inputs.wasm-pack-version }}"
        echo "✅wasm-pack installed!"

    - name: Print wasm-pack version
      shell: bash
      run: |
        echo "🔎Now ensuring wasm-pack is available..."
        wasm-pack --version
        echo "✅wasm-pack ready!"
