name: "Install wasm-pack"
description: "Install wasm-pack for Rust"

inputs:
  shell:
    description: "The shell used to run commands"
    required: false
    default: "bash"

runs:
  using: "composite"
  steps:
    - name: Run installation script
      shell: ${{ inputs.shell }}
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Print version
      shell: ${{ inputs.shell }}
      run: wasm-pack --version
