name: Test find-critical-todos
description: Tests for find-critical-todos.

runs:
  using: composite
  steps:
    - uses: giancosta86/gauntlet/actions/setup-elvish-action@v1

    - shell: elvish {0}
      run: echo 🎭 Looking for inexistent critical TODOs...

    - uses: ./actions/find-critical-todos
      with:
        files: README.md
        working-directory: tests/unknown-tech

    - shell: elvish {0}
      run: echo ✅ Tests OK!
