name: Test find-critical-todos
description: Tests for find-critical-todos.

runs:
  using: composite
  steps:
    - uses: ./actions/setup-elvish-context

    - shell: elvish {0}
      run: echo 🎭 Looking for inexistent critical TODOs...

    - uses: ./actions/find-critical-todos
      with:
        files: "**.txt"
        working-directory: tests/unknown-tech

    - shell: elvish {0}
      run: echo ✅ Tests OK!
