use os
use path
use github.com/giancosta86/ethereal/v1/console
use github.com/giancosta86/ethereal/v1/highlight

fn print-wasm-descriptor {
  var generated-package-json = (path:join pkg package.json)

  if (os:is-regular $generated-package-json) {
    console:section &emoji=🧬 'package.json generated by wasm-pack and pipeline' {
      highlight:file $generated-package-json json
    }
  } else {
    echo 💭 No package.json file was generated...
  }
}