use path
use github.com/giancosta86/ethereal/v1/console
use github.com/giancosta86/ethereal/v1/highlight

fn print-wasm-descriptor {
  console:section &emoji=📦 'package.json generated by wasm-pack and pipeline' {
    path:join pkg package.json |
      highlight:file (all) json
  }
}