name: Detect branch version
description: Extracts the version from the name of the current Git branch, returning a variety of info.

outputs:
  branch:
    description: Current Git branch.
    value: ${{ steps.detect-version.outputs.branch }}

  version:
    description: Version detected from the Git branch - always without prefix.
    value: ${{ steps.detect-version.outputs.version }}

  escaped-version:
    description: Escaped version - for example, with `\.` in lieu of `.` - for regular expressions.
    value: ${{ steps.detect-version.outputs.escaped-version }}

  major:
    description: Major component of the version.
    value: ${{ steps.detect-version.outputs.major }}

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/init-aurora-github@v11.0.3

    - id: detect-version
      shell: elvish {0}
      run: |
        use github.com/giancosta86/aurora-github/actions/detect-branch-version
        detect-branch-version:main
