name: Detect branch version
description: Extracts the version from the name of the current Git branch, returning both.

outputs:
  branch:
    description: The current Git branch.
    value: ${{ steps.detect-version.outputs.branch }}

  version:
    description: The version detected from the Git branch - always without prefix.
    value: ${{ steps.detect-version.outputs.version }}

  escaped-version:
    description: The escaped version - for example, with '\.' in lieu of '.' - suitable for regular expressions.
    value: ${{ steps.detect-version.outputs.escaped-version }}

  major:
    description: The 'major' component of the version.
    value: ${{ steps.detect-version.outputs.major }}

runs:
  using: composite
  steps:
    - name: Setup Python context
      shell: bash
      run: |
        pythonPath="${{ github.action_path }}/../../core/python"
        echo "PYTHONPATH=$pythonPath" >> $GITHUB_ENV

    - name: Call the Python implementation
      id: detect-version
      shell: python
      run: |
        from core.detect_branch_version import detect_branch_version_info

        detect_branch_version_info().write_to_github_output()
