name: Detect branch version
description: Extracts the current version from the Git branch name, returning both.

inputs:
  shell:
    description: The shell used to run commands.
    required: false
    default: bash

outputs:
  branch:
    description: The current Git branch.
    value: ${{ steps.detect-version.outputs.branch }}

  version:
    description: The version detected from the Git branch, without prefix.
    value: ${{ steps.detect-version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Detect version from branch
      id: detect-version
      shell: ${{ inputs.shell }}
      run: |
        branch="${{ github.head_ref }}"

        version="$(echo "$branch" | sed 's/^[bv]//')"
        echo "Detected version: '$version'" 

        echo "branch=$branch" >> $GITHUB_OUTPUT
        echo "version=$version" >> $GITHUB_OUTPUT
