name: Detect branch version
description: Extracts the current version from the Git branch name, returning both.

inputs:
  shell:
    description: The shell used to run commands.
    required: false
    default: bash

outputs:
  branch:
    description: The current Git branch.
    value: ${{ steps.detect-branch.outputs.branch }}

  version:
    description: The version detected from the Git branch, without prefix.
    value: ${{ steps.detect-version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Detect branch
      id: detect-branch
      shell: ${{ inputs.shell }}
      run: |
        branch="${{ github.head_ref }}"

        echo "Detected Git branch: '$branch'"      

        if [[ ! $branch =~ ^b?[0-9](\.[0-9](\.[0-9])?)?$ ]]
        then
          echo "Invalid semver branch format: '$branch'"
          exit 1
        fi

        echo "branch=$branch" >> $GITHUB_OUTPUT

    - name: Detect version from branch
      id: detect-version
      shell: ${{ inputs.shell }}
      run: |
        branch="${{ steps.detect-branch.outputs.branch }}"

        version="$(echo "$branch" | sed 's/^b//')"
        echo "Detected version: '$version'" 

        echo "version=$version" >> $GITHUB_OUTPUT
