name: Detect branch version
description: Extracts the version from the name of the current Git branch, returning both.

outputs:
  branch:
    description: The current Git branch.
    value: ${{ steps.detect-version.outputs.branch }}

  version:
    description: The version detected from the Git branch - always without prefix.
    value: ${{ steps.detect-version.outputs.version }}

  escaped-version:
    description: The escaped version - for example, with '\.' in lieu of '.' - suitable for regular expressions.
    value: ${{ steps.detect-version.outputs.escaped-version }}

  major:
    description: The 'major' component of the version.
    value: ${{ steps.detect-version.outputs.major }}

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v10.3.0

    - id: detect-version
      shell: elvish {0}
      run: |
        use aurora-github/core
        use aurora-github/branch-version

        core:map-to-output (branch-version:detect)
