name: Test detect-branch-version
description: Tests for detect-branch-version.

runs:
  using: composite
  steps:
    - uses: ./actions/detect-branch-version
      id: detector

    - uses: ./actions/run-velvet-code
      with:
        code: |
          >> 'Action outputs' {
            >> 'branch' {
              put '${{ steps.detector.outputs.branch }}' |
                should-not-be-empty
            }

            >> 'version' {
              put '${{ steps.detector.outputs.version }}' |
                should-not-be-empty
            }

            >> 'escaped version' {
              put '${{ steps.detector.outputs.escaped-version }}' |
                should-contain \.
            }

            >> 'major component' {
              put '${{ steps.detector.outputs.major }}' |
                should-not-be-empty
            }
          }
