name: Test detect-branch-version

runs:
  using: composite
  steps:
    - uses: ./actions/detect-branch-version
      id: detector

    - name: Branch should not be empty
      shell: bash
      run: |
        branch="${{ steps.detector.outputs.branch }}"

        echo "🔎Branch retrieved from action: '$branch'"
        if [[ -z "$branch" ]] 
        then
          echo "❌The branch should not be empty!" >&2
          exit 1
        fi

    - name: The detected branch should be the one starting the pull request for this test
      shell: bash
      run: |
        headRef="${{ github.head_ref }}"
        branch="${{ steps.detector.outputs.branch }}"

        echo "🔎Head ref in pull request: '$headRef'"

        if [[ "$branch" != "$headRef" ]] 
        then
          echo "❌The branch ('$branch') should match the head_ref ('$headRef')!" >&2
          exit 1
        fi

    - name: Version should not be empty
      shell: bash
      run: |
        version="${{ steps.detector.outputs.version }}"

        echo "🔎Version retrieved from action: '$version'"
        if [[ -z "$version" ]] 
        then
          echo "❌The version should not be empty!" >&2
          exit 1
        fi

    - name: Escaped version should include escaped dots
      shell: bash
      run: |
        escapedVersion="${{ steps.detector.outputs.escaped-version }}"

        echo "🔎Escaped version retrieved from action: '$escapedVersion'"
        if ! echo "$escapedVersion"  | grep -Pq "\\\." 
        then
          echo "❌The escaped version should include '\.'!" >&2
          exit 1
        fi

    - name: Major component should not be empty
      shell: bash
      run: |
        major="${{ steps.detector.outputs.major }}"

        echo "🔎Major version component: '$major'"
        if [[ -z "$major" ]] 
        then
          echo "❌The major component should not be empty!" >&2
          exit 1
        fi
