name: Test detect-branch-version

runs:
  using: composite
  steps:
    - uses: ./actions/detect-branch-version
      id: detector

    - name: Test branch
      shell: bash
      run: |
        branch="${{ steps.detector.outputs.branch }}"

        echo "🔎Branch retrieved from action: '$branch'"
        [[ -z $branch ]] && exit 1

    - name: Test version
      shell: bash
      run: |
        version="${{ steps.detector.outputs.version }}"

        echo "🔎Version retrieved from action: '$version'"
        [[ -z $version ]] && exit 1
