name: Test detect-branch-version

runs:
  using: composite
  steps:
    - uses: ./actions/detect-branch-version
      id: detector

    - name: Test branch
      shell: bash
      run: |
        branch="${{ steps.detector.outputs.branch }}"

        echo "🔎Branch retrieved from action: '$branch'"
        if [[ -z $branch ]] 
        then
          echo 'Branch should not be null!' >&2
          exit 1
        fi

    - name: Test version
      shell: bash
      run: |
        version="${{ steps.detector.outputs.version }}"

        echo "🔎Version retrieved from action: '$version'"
        if [[ -z $version ]] 
        then
          echo 'Version should not be null!' >&2
          exit 1
        fi

        [ -z $version ] && echo "Empty version"
