name: Test verify-rust-crate

runs:
  using: composite
  steps:
    - uses: ./actions/inject-branch-version
      with:
        artifact-descriptor: ./tests/rust-crate/Cargo.toml

    - uses: ./actions/verify-rust-crate
      with:
        project-directory: ./tests/rust-crate
