name: Test verify-rust-crate
description: Tests for verify-rust-crate.

runs:
  using: composite
  steps:
    - uses: ./actions/verify-rust-crate
      with:
        working-directory: tests/rust-crate
        check-license: false
