name: Test run-custom-tests

runs:
  using: composite
  steps:
    - uses: ./.github/test-actions/test-run-custom-tests/scenario
      with:
        strategy: bash
        root-directory: tests/custom/bash

    - uses: ./.github/test-actions/test-run-custom-tests/scenario
      with:
        strategy: elvish
        root-directory: tests/custom/elvish

    - uses: ./.github/test-actions/test-run-custom-tests/scenario
      with:
        strategy: nodejs
        root-directory: tests/custom/nodejs

    - uses: ./.github/test-actions/test-run-custom-tests/scenario
      with:
        strategy: rust
        root-directory: tests/custom/rust

    - shell: bash
      run: echo "🎭Trying to run tests from an inexistent directory..."

    - uses: ./actions/run-custom-tests
      with:
        root-directory: tests/custom/TOTALLY_INEXISTENT
        optional: true

    - shell: bash
      run: echo "🎭Trying to run tests from a directory containing no tests..."

    - uses: ./actions/run-custom-tests
      with:
        root-directory: tests/custom
        optional: true
