name: Test run-elvish-tests
description: Tests for run-elvish-tests.

runs:
  using: composite
  steps:
    - uses: giancosta86/gauntlet/actions/setup-elvish-action@v1

    - shell: elvish {0}
      run: echo 🎭 Running the custom verification script...

    - uses: ./actions/run-elvish-tests
      with:
        working-directory: tests/elvish

    - shell: elvish {0}
      working-directory: tests/elvish
      run: |
        use os

        echo 🔎 Now checking the custom script output...

        if (not (os:is-regular script-out.txt)) {
          fail 'Missing test output script!'
        }

        put velvet*[nomatch-ok].txt |
          if (not-eq [(all)] []) {
            fail 'Velvet tests must not run when running the test script!'
          }

        echo ✅ Test script run OK!

    - shell: elvish {0}
      run: echo 🎭 Running tests from a directory containing Velvet scripts...

    - uses: ./.github/test-actions/test-run-elvish-tests/velvet-scenario
      with:
        header: Now checking the Velvet test output...
        first-output-should-exist: true
        second-output-should-exist: true

    - uses: ./.github/test-actions/test-run-elvish-tests/velvet-scenario
      with:
        header: Now running a specific Velvet script...
        velvet-scripts: second
        first-output-should-exist: false
        second-output-should-exist: true

    - uses: ./.github/test-actions/test-run-elvish-tests/velvet-scenario
      with:
        header: Now running with a wildcard...
        velvet-scripts: "*cond*"
        first-output-should-exist: false
        second-output-should-exist: true

    - uses: ./.github/test-actions/test-run-elvish-tests/velvet-scenario
      with:
        header: Now running with metadata...
        include-metadata: true
        first-output-should-exist: true
        second-output-should-exist: true
