name: Test run-elvish-tests
description: Tests for run-elvish-tests.

runs:
  using: composite
  steps:
    - uses: giancosta86/gauntlet/actions/setup-elvish-action@v1.0.0 #TODO! V1 here

    - shell: elvish {0}
      run: echo 🎭 Running tests from a directory containing an Elvish verification script...

    - uses: ./actions/run-elvish-tests
      with:
        working-directory: tests/elvish/script

    - shell: elvish {0}
      working-directory: tests/elvish/script
      run: |
        echo 🎭 Now checking the custom script output...

        var test-output = (slurp < out.txt)

        if (not-eq $test-output 'TEST OK') {
          fail 'Unexpected test output: '$test-output
        }

    - shell: elvish {0}
      run: echo 🎭 Running tests from a directory containing Velvet scripts...

    - uses: ./actions/run-elvish-tests
      with:
        working-directory: tests/elvish/velvet

    - shell: elvish {0}
      working-directory: tests/elvish/velvet
      run: |
        echo 🎭 Now checking the Velvet test output...

        var first-test-output = (slurp < out.txt)

        if (not-eq $first-test-output 'FIRST VELVET TEST OK') {
          fail 'Unexpected 1st test output: '$first-test-output
        }

        var second-test-output = (slurp < out-2.txt)

        if (not-eq $second-test-output 'SECOND VELVET TEST OK') {
          fail 'Unexpected 2nd test output: '$second-test-output
        }

    - shell: elvish {0}
      working-directory: tests/elvish/velvet
      run: |
        echo 🎭 Now running a specific Velvet script...
        rm *.txt

    - uses: ./actions/run-elvish-tests
      with:
        working-directory: tests/elvish/velvet
        velvet-scripts: protocol-2

    - shell: elvish {0}
      working-directory: tests/elvish/velvet
      run: |
        use os

        echo 🎭 Now checking the specific Velvet test output...

        if (os:is-regular out.txt) {
          fail 'Only the second protocol script should run!'
        }

        var second-test-output = (slurp < out-2.txt)

        if (not-eq $first-test-output 'SECOND VELVET TEST OK') {
          fail 'Unexpected 2nd test output: '$second-test-output
        }
