name: Test run-elvish-tests
description: Tests for run-elvish-tests.

runs:
  using: composite
  steps:
    - uses: ./actions/setup-elvish-context

    - shell: elvish {0}
      run: echo 🎭 Running tests from a directory containing an Elvish verification script...

    - uses: ./actions/run-elvish-tests
      with:
        working-directory: tests/elvish/script

    - shell: elvish {0}
      run: echo 🎭 Now checking the custom script output...

    - uses: ./actions/run-velvet-code
      with:
        working-directory: tests/elvish/script
        code: |
          >> 'The tests' {
            >> 'should produce the expected output file' {
              slurp < out.txt |
                should-be 'TEST OK'
            }
          }

    - shell: elvish {0}
      run: echo 🎭 Running tests from a directory containing Velvet scripts...

    - uses: ./actions/run-elvish-tests
      with:
        working-directory: tests/elvish/velvet

    - shell: elvish {0}
      run: echo 🎭 Now checking the Velvet test output...

    - uses: ./actions/run-velvet-code
      with:
        working-directory: tests/elvish/velvet
        code: |
          >> 'The tests' {
            >> 'should produce the expected output file' {
              slurp < out.txt |
                should-be 'TEST OK'
            }
          }
