name: Test publish-rust-wasm

runs:
  using: composite
  steps:
    - uses: ./actions/publish-rust-wasm
      with:
        project-directory: tests/rust-wasm
        dry-run: true
        wasm-pack-version: 0.13.1
        npm-scope: giancosta86
