name: generate-wasm-target
description: Generates the source files for a WebAssembly target from a Rust project.

inputs:
  target:
    description: The target of the 'wasm-pack build' command.

  npm-scope:
    description: The package scope or "<ROOT>", for npm targets.

  nodejs-version:
    description: The "engines / node" version within package.json.

  pnpm-version:
    description: The "packageManager" reference to pnpm within package.json.

  development:
    description: Enable debugging info.

  target-directory:
    description: Directory (relative to 'project-directory') for the generated target.

  project-directory:
    description: The directory containing Cargo.toml.
    default: "."

runs:
  using: composite
  steps:
    - name: Validate inputs
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        if [[ -z "${{ inputs.target }}" ]]
        then
          echo "仇Missing action input: 'target'!" >&2
          exit 1
        fi

        if [[ -z "${{ inputs.development }}" ]]
        then
          echo "仇Missing action input: 'development'!" >&2
          exit 1
        fi

        if [[ -z "${{ inputs.target-directory }}" ]]
        then
          echo "仇Missing action input: 'target-directory'!" >&2
          exit 1
        fi

    - name: Parse npm scope
      id: parse-npm-scope
      if: ${{ inputs.npm-scope != '' }}
      uses: giancosta86/aurora-github/actions/parse-npm-scope@v8.0.0
      with:
        scope: ${{ inputs.npm-scope }}

    - name: Generate the WebAssembly target
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        target="${{ inputs.target }}"
        echo "游닌Target: '$target'"

        echo "游닌Requested npm-scope: '${{ inputs.npm-scope }}'"

        scope="${{ steps.parse-npm-scope.outputs.actual-scope }}"
        echo "游댍Actual npm scope: '$scope'"

        development="${{ inputs.development }}"
        echo "游닌Development? $development"

        echo "Project directory: '${{ inputs.project-directory }}'"

        targetDirectory="${{ inputs.target-directory }}"
        echo "游닌Target directory: '$targetDirectory'"

        echo "游닍Generating the WebAssembly project files..."

        if [[ "$development" == "true" ]]
        then
          modeArg="--dev"
        else
          modeArg="--release"
        fi

        if [[ -n "$scope" ]]
        then
          scopeArg="--scope $scope"
        else
          scopeArg=""
        fi

        wasm-pack build --target "$target" $modeArg $scopeArg --out-dir "$targetDirectory"

    - name: Inject the requested NodeJS version into package.json
      if: ${{ inputs.nodejs-version != '' }}
      shell: bash
      working-directory: ${{ inputs.project-directory }}/${{ inputs.target-directory }}
      run: |
        if [[ ! -f "package.json" ]]
        then
          echo "仇깛ackage.json was not generated for this target - cannot inject the requested NodeJS version!"
          exit 1
        fi

        nodejsVersion="${{ inputs.nodejs-version }}"
        echo "游빏Injecting the requested NodeJS version ('$nodejsVersion')..."

        tempDescriptor="$(mktemp)"
        jq '.engines.node = "'"$nodejsVersion"'"' package.json > "$tempDescriptor"
        mv "$tempDescriptor" package.json

    - name: Inject the requested pnpm version into package.json
      if: ${{ inputs.pnpm-version != '' }}
      shell: bash
      working-directory: ${{ inputs.project-directory }}/${{ inputs.target-directory }}
      run: |
        if [[ ! -f "package.json" ]]
        then
          echo "仇깛ackage.json was not generated for this target - cannot inject the requested pnpm version!"
          exit 1
        fi

        pnpmVersion="${{ inputs.pnpm-version }}"
        echo "游빏Injecting the requested pnpm version ('$pnpmVersion')..."

        tempDescriptor="$(mktemp)"
        jq '.packageManager = "pnpm@'"$pnpmVersion"'"' package.json > "$tempDescriptor"
        mv "$tempDescriptor" package.json

    - name: Display the generated package.json descriptor
      shell: bash
      working-directory: ${{ inputs.project-directory }}/${{ inputs.target-directory }}
      run: |
        if [[ -f "package.json" ]]
        then
          echo "游닍Generated package.json descriptor for the '${{ inputs.target}}' target:"
          jq -C '.' package.json
        else
          echo "游눬No package.json descriptor generated for the '${{ inputs.target}}' target..."
        fi

    - name: Display success message
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        echo "九WebAssembly target ready in '${{ inputs.target-directory }}'!"
