name: Generate Rust web assembly target
description: Generates the source files for a WebAssembly target from a Rust project.

inputs:
  target:
    description: The target of the `wasm-pack build` command.

  npm-scope:
    description: The package scope or `<ROOT>`, for npm targets.

  nodejs-version:
    description: The `engines -> node` version within package.json.

  pnpm-version:
    description: The `packageManager` reference to pnpm within package.json.

  development:
    description: Enable debugging info.

  target-directory:
    description: Directory (relative to `project-directory`) for the generated target.

  project-directory:
    description: The directory containing `Cargo.toml`.
    default: "."

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v11.0.0

    - name: Generate the WebAssembly target
      shell: elvish {0}
      working-directory: ${{ inputs.project-directory }}
      run: |
        use aurora-github/ci-cd/input
        use aurora-github/rust/wasm-pack

        wasm-pack:generate-target [
          &target=(input:string target '${{ inputs.target }}')

          &npm-scope=(input:string npm-scope '${{ inputs.npm-scope }}')

          &nodejs-version=(input:string &optional nodejs-version '${{ inputs.nodejs-version }}')

          &pnpm-version=(input:string &optional pnpm-version '${{ inputs.pnpm-version }}')

          &development=(input:bool development '${{ inputs.development }}')

          &target-directory=(input:string target-directory '${{ inputs.target-directory }}')
        ]
