name: generate-wasm-target
description: Generates the source files for a WebAssembly target from a Rust project.

inputs:
  target:
    description: The target of the 'wasm-pack build' command.

  npm-scope:
    description: The package scope or "<ROOT>", for npm targets.

  nodejs-version:
    description: The "engines / node" version within package.json.

  pnpm-version:
    description: The "packageManager" reference to pnpm within package.json.

  development:
    description: Enable debugging info.

  target-directory:
    description: Directory (relative to 'project-directory') for the generated target.

  project-directory:
    description: The directory containing Cargo.toml.
    default: "."

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v10.3.0

    - name: Generate the WebAssembly target
      shell: elvish {0}
      working-directory: ${{ inputs.project-directory }}
      run: |
        use aurora-github/core
        use aurora-github/npm
        use aurora-github/wasm

        var npm-scope-input = '${{ inputs.npm-scope }}'

        var npm-scope = (
          core:ternary (core:not-empty $npm-scope-input) (npm:parse-scope $npm-scope-input) ''
        )

        wasm:generate-target [
          &target=(core:require-input target '${{ inputs.target }}')
          &development=(core:require-input development '${{ inputs.development }}')
          &target-directory=(core:require-input target-directory '${{ inputs.target-directory }}')
          &nodejs-version='${{ inputs.nodejs-version }}'
          &pnpm-version='${{ inputs.pnpm-version }}'
          &npm-scope=$npm-scope
        ]
