name: Test verify-python-package

runs:
  using: composite
  steps:
    - shell: bash
      run: echo "🎭Verifying 🐍Python library..."

    - uses: ./actions/verify-python-package
      with:
        project-directory: tests/python-lib
