name: Test verify-python-package
description: Tests for verify-python-package.

runs:
  using: composite
  steps:
    - uses: ./actions/verify-python-package
      with:
        working-directory: tests/python-lib
