name: Update and check subpath exports in the npm test project.
description: Scenario for check-subpath-exports.

inputs:
  header:
    description: Header for this scenario.

  jq-operation:
    description: jq operation altering the package.json descriptor.

runs:
  using: composite
  steps:
    - shell: elvish {0}
      run: echo 🎭 ${{inputs.header}}

    - shell: elvish {0}
      working-directory: tests/npm-package
      run: |
        use github.com/giancosta86/ethereal/v1/console
        use github.com/giancosta86/ethereal/v1/edit

        edit:json package.json '${{ inputs.jq-operation }}'

        console:section &emoji=🔎 'The "exports" field is' {
          jq -C '.exports' package.json
        }

    - uses: ./actions/check-subpath-exports
      with:
        working-directory: tests/npm-package
