name: Test install-system-packages
description: Tests for install-system-packages.

runs:
  using: composite
  steps:
    - uses: giancosta86/gauntlet/actions/setup-elvish-action@v1

    - shell: elvish {0}
      run: |
        use github.com/giancosta86/gauntlet/v1/env

        env:set expected-command sponge

    - shell: elvish {0}
      run: echo 🎭 Checking preconditions...

    - uses: ./actions/run-elvish-tests
      with:
        working-directory: ${{ github.action_path }}
        velvet-scripts: preconditions

    - shell: elvish {0}
      run: echo 🎭 Running unconditional installation...

    - uses: ./actions/install-system-packages
      with:
        packages: jq, moreutils

    - uses: ./actions/run-elvish-tests
      with:
        working-directory: ${{ github.action_path }}
        velvet-scripts: action

    - shell: elvish {0}
      run: echo 🎭 Running conditional installation for existing command - which should be skipped...

    - uses: ./actions/install-system-packages
      with:
        required-command: ${{ env.expected-command }}
        packages: moreutils

    - shell: elvish {0}
      run: echo ✅ All tests OK!
