name: Enforce branch version
description: Ensures that the version in the artifact descriptor matches the Git branch version - by injecting or merely by checking.

inputs:
  mode:
    description: How to enforce the branch version. Can be "inject", "check" or "skip".

  artifact-descriptor:
    description: Relative path to the artifact descriptor.

  project-directory:
    description: The directory containing the project.
    default: .

runs:
  using: composite
  steps:
    - name: Validate inputs
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        echo "游닌Requested mode: '${{ inputs.mode }}'"

        case "${{ inputs.mode }}" in
          inject | check)
            ;;

          skip)
            echo "游눬Skipping branch version enforcement, as requested..."
            ;;

          *)
            echo "仇Invalid value for 'mode' input: '${{ inputs.mode }}'!" >&2
            exit 1
        esac

    - name: Ensure the descriptor exists
      if: ${{ inputs.mode != 'skip' }}
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        requestedDescriptor="${{ inputs.artifact-descriptor }}"
        echo "游닌Requested descriptor: '$requestedDescriptor'"

        if [[ -n "$requestedDescriptor" ]]
        then
          echo "九ㅔrtifact descriptor provided!"
          artifactDescriptor="$requestedDescriptor"
        else
          echo "游댩Trying to detect the artifact descriptor..."

          if [[ -f "package.json" ]]
          then
            echo "游닍package.json descriptor for NodeJS detected!"
            artifactDescriptor="package.json"
          elif [[ -f "Cargo.toml" ]]
          then
            echo "游Cargo.toml descriptor for Rust detected!"
            artifactDescriptor="Cargo.toml"
          elif [[ -f "pom.xml" ]]
          then
            echo "游뿼pom.xml descriptor for Maven detected!"
            artifactDescriptor="pom.xml"
          elif [[ -f "build.gradle" ]]
          then
            echo "游냊build.gradle descriptor for Gradle detected!"
            artifactDescriptor="build.gradle"
          elif [[ -f "build.gradle.kts" ]]
          then
            echo "游냊build.gradle.kts descriptor for Gradle detected!"
            artifactDescriptor="build.gradle.kts"
          else
            echo "游눬No supported descriptors found..."
            artifactDescriptor=""
          fi
        fi

        echo "游댍Artifact descriptor: '$artifactDescriptor'"

        if [[ -z "$artifactDescriptor" ]]
        then
          echo "仇No artifact descriptor requested - and none can be detected!" >&2
          exit 1
        fi

        if [[ ! -f "$artifactDescriptor" ]]
        then
          echo "仇Cannot find the artifact descriptor file: '$artifactDescriptor'!" >&2
          exit 1
        fi

        echo "artifactDescriptor=$artifactDescriptor" >> $GITHUB_ENV

    - name: Infer the technology
      if: ${{ inputs.mode != 'skip' }}
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        case "$(basename "$artifactDescriptor")" in
          package.json)
            tech="nodejs"
            ;;

          Cargo.toml)
            tech="rust"
            ;;

          pom.xml)
            tech="maven"
            ;;

          build.gradle | build.gradle.kts)
            tech="gradle"
            ;;

          *)
            tech=""
        esac

        echo "游뱄Inferred technology: '${tech}'"
        echo "tech=$tech" >> $GITHUB_ENV

    - uses: giancosta86/aurora-github/actions/detect-branch-version@v8.1.0
      if: ${{ inputs.mode != 'skip' }}
      id: version-detector

    - name: Inject the branch version into the descriptor
      if: ${{ inputs.mode == 'inject' }}
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        version="${{ steps.version-detector.outputs.version }}"
        echo "游댍Detected branch version: '$version'"

        echo "游빏Injecting the branch version into the descriptor..."
        sed -i "s/0\.0\.0/${version}/g" "$artifactDescriptor"
        echo "九Version injected!"

    - name: Print the content of the artifact descriptor
      if: ${{ inputs.mode != 'skip' }}
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        case "$tech" in
          nodejs)
            echo "游닍NodeJS descriptor ($artifactDescriptor):"
            jq -C . "$artifactDescriptor"
            echo "游닍游닍游닍"
            ;;

          rust)
            echo "游Rust crate descriptor ($artifactDescriptor):"
            cat "$artifactDescriptor"
            echo "游游游"
            ;;

          maven)
            echo "游뿼Maven project descriptor ($artifactDescriptor):"
            cat "$artifactDescriptor"
            echo "游뿼游뿼游뿼"
            ;;

          gradle)
            echo "游냊Gradle project descriptor ($artifactDescriptor):"
            cat "$artifactDescriptor"
            echo "游냊游냊游냊"
            ;;

          *)
            echo "游꾸Unknown tech descriptor ($artifactDescriptor):"
            cat "$artifactDescriptor"
            echo "游꾸游꾸游꾸"
        esac

    - name: Extract the NodeJS package version
      if: ${{ inputs.mode == 'check' && env.tech == 'nodejs' }}
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        echo "游닋Extracting the artifact version from the 游닍NodeJS descriptor ('$artifactDescriptor')..."

        artifactVersion="$(jq -r .version "$artifactDescriptor")"

        echo "artifactVersion=$artifactVersion" >> $GITHUB_ENV

    - name: Extract the Rust crate version
      if: ${{ inputs.mode == 'check' && env.tech == 'rust' }}
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        echo "游닋Extracting the artifact version from the 游Rust descriptor ('$artifactDescriptor')..."

        artifactVersion="$(grep '^version' Cargo.toml | cut -d '"' -f2)"

        echo "artifactVersion=$artifactVersion" >> $GITHUB_ENV

    - name: Extract the Maven project version
      if: ${{ inputs.mode == 'check' && env.tech == 'maven' }}
      shell: python
      working-directory: ${{ inputs.project-directory }}
      run: |
        import os
        import xml.etree.ElementTree as ET

        tree = ET.parse('pom.xml')
        root = tree.getroot()
        namespaces = {'mvn': root.tag.split('}')[0].strip('{}')}

        version = root.find('.//mvn:version', namespaces).text

        with open(os.environ['GITHUB_ENV'], 'a') as env_file:
            env_file.write(f"version={version}\n")

    - name: Extract the Gradle project version
      if: ${{ inputs.mode == 'check' && env.tech == 'gradle' }}
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        echo "游닋Extracting the artifact version from the 游냊Gradle descriptor ('$artifactDescriptor')..."

        artifactVersion="$(cat build.gradle.kts |  grep -P '^version\s+=\s+["'\''].+?["'\'']$' | cut -d '=' -f 2 | sed "s/[\"' ]//g")"

        echo "artifactVersion=$artifactVersion" >> $GITHUB_ENV

    - name: Ensure the artifact version matches the branch version
      if: ${{ inputs.mode == 'check' && env.tech != '' }}
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        branchVersion="${{ steps.version-detector.outputs.version }}"
        echo "游댍Branch version: '$branchVersion'"
        echo "游댍Artifact version: '$artifactVersion'"

        if [[ "$artifactVersion" == "$branchVersion" ]]
        then
          echo "九The descriptor version matches the branch version!"
        else
          echo "仇The descriptor version and the branch version do not match!" >&2
          exit 1
        fi

    - name: Check unknown artifact version
      if: ${{ inputs.mode == 'check' && env.tech == '' }}
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        branchVersion="${{ steps.version-detector.outputs.version }}"
        echo "游댍Branch version: '$branchVersion'"

        echo "游댍Ensuring the branch version exists in the 游꾸unknown tech descriptor ('$artifactDescriptor')..."

        if grep -q "$branchVersion" "$artifactDescriptor"
        then
          echo "九Version found in the descriptor!"
        else
          echo "仇The branch version cannot be found in the artifact descriptor!" >&2
          exit 1
        fi
