name: Enforce branch version
description: Ensures that the version in the artifact descriptor matches the Git branch version - by injecting or merely by checking.

inputs:
  mode:
    description: How to enforce the branch version. Can be "inject", "check" or "skip".

  artifact-descriptor:
    description: Relative path to the artifact descriptor.

  project-directory:
    description: The directory containing the project.
    default: .

runs:
  using: composite
  steps:
    - name: Setup Python context
      shell: bash
      run: |
        pythonPath="${{ github.action_path }}/../.."
        echo "PYTHONPATH=$pythonPath" >> $GITHUB_ENV

        echo "INPUT_MODE=${{ inputs.mode }}" >> $GITHUB_ENV
        echo "INPUT_ARTIFACT_DESCRIPTOR=${{ inputs.artifact-descriptor }}" >> $GITHUB_ENV
        echo "INPUT_PROJECT_DIRECTORY=${{ inputs.project-directory }}" >> $GITHUB_ENV

    - name: Call the Python implementation
      shell: python
      run: |
        from core.enforce_branch_version import enforce_branch_version, Inputs

        inputs = Inputs.from_env()

        enforce_branch_version(inputs)
