name: Enforce branch version
description: Ensures that the version in the artifact descriptor matches the Git branch version - by injecting or merely by checking.

inputs:
  mode:
    description: How to enforce the branch version. Can be "inject", "check" or "skip".

  artifact-descriptor:
    description: Relative path to the artifact descriptor.

  project-directory:
    description: The directory containing the project.
    default: .

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v10.3.0

    - shell: elvish {0}
      run: |
        use aurora-github/branch-version

        branch-version:enforce '${{ inputs.project-directory}}' '${{ inputs.mode }}' &descriptor-name='${{ inputs.artifact-descriptor }}'
