name: Enforce branch version
description: Ensures that the version in the artifact descriptor matches the Git branch version - by injecting or merely by checking.

inputs:
  mode:
    description: How to enforce the branch version. Can be `inject`, `check` or `skip`.

  artifact-descriptor:
    description: Relative path to the artifact descriptor.

  project-directory:
    description: The directory containing the project.
    default: .

runs:
  using: composite
  steps:
    - uses: giancosta86/aurora-github/actions/setup-elvish-context@v11.0.0

    - shell: elvish {0}
      working-directory: ${{ inputs.project-directory }}
      run: |
        use github.com/giancosta86/aurora-github/branch-version
        use github.com/giancosta86/aurora-github/ci-cd/input

        var mode = (
          input:enum mode '${{ inputs.mode }}' [inject check skip]
        )

        branch-version:enforce $mode
      env:
        artifact-descriptor: ${{ inputs.artifact-descriptor }}
