name: Verify npm package
description: Verifies the source files of a NodeJS package - by running its 'verify' script within the 'scripts' section of 'package.json'.

inputs:
  crash-on-critical-todos:
    description: Crash the workflow if critical TODOs are found.
    default: true

  source-file-regex:
    description: PCRE pattern describing the source files.
    default: '^\.\/(src|tests)\/.+\.(c|m)?(j|t)sx?$'

  enforce-branch-version:
    description: The "mode" parameter for "enforce-branch-version".
    default: inject

  enforce-esm:
    description: Verify that the "type" field is "module" - to create an ESM package.
    default: true

  check-subpath-exports:
    description: Run check-subpath-exports after the "verify" package script.
    default: true

  project-directory:
    description: The directory containing package.json.
    default: .

runs:
  using: composite
  steps:
    - name: Validate inputs
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        if [[ -z "${{ inputs.crash-on-critical-todos }}" ]]
        then
          echo "❌Missing action input: 'crash-on-critical-todos'!" >&2
          exit 1
        fi

        if [[ -z "${{ inputs.source-file-regex }}" ]]
        then
          echo "❌Missing action input: 'source-file-regex'!" >&2
          exit 1
        fi

        if [[ -z "${{ inputs.enforce-esm }}" ]]
        then
          echo "❌Missing action input: 'enforce-esm'!" >&2
          exit 1
        fi

        if [[ -z "${{ inputs.check-subpath-exports }}" ]]
        then
          echo "❌Missing action input: 'check-subpath-exports'!" >&2
          exit 1
        fi

        if [[ ! -f "package.json" ]]
        then
          echo "❌The package.json descriptor file does not exist!!" >&2
          exit 1
        fi

    - name: Enforce branch version
      uses: giancosta86/aurora-github/actions/enforce-branch-version@v7.0.0
      with:
        mode: ${{ inputs.enforce-branch-version }}
        project-directory: ${{ inputs.project-directory }}

    - name: Enforce ESM
      if: ${{ inputs.enforce-esm == 'true' }}
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        packageType="$(jq -r .type package.json)"
        expectedType="module"

        echo "🔎Detected package type: '$packageType'"

        if [[ "$packageType" == "$expectedType" ]]
        then
          echo "✅This npm package is based on ESM!"
        else
          echo "❌The package type must be '$expectedType'!" >&2
          exit 1
        fi

    - name: Setup NodeJS context
      uses: giancosta86/aurora-github/actions/setup-nodejs-context@v7.0.0
      with:
        project-directory: ${{ inputs.project-directory }}

    - name: Run the 'verify' script from package.json
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        echo "🔎Now running the 'verify' package.json script..."
        pnpm verify
        echo "✅'verify' script successful!"

    - name: Check subpath exports
      if: ${{ inputs.check-subpath-exports == 'true' }}
      uses: giancosta86/aurora-github/actions/check-subpath-exports@v7.0.0
      with:
        project-directory: ${{ inputs.project-directory }}

    - name: Run optional custom tests from the 'tests' directory
      uses: giancosta86/aurora-github/actions/run-custom-tests@v7.0.0
      with:
        optional: true
        root-directory: ${{ inputs.project-directory }}/tests

    - name: Check for critical TODOs
      uses: giancosta86/aurora-github/actions/find-critical-todos@v7.0.0
      with:
        source-file-regex: ${{ inputs.source-file-regex }}
        crash-on-found: ${{ inputs.crash-on-critical-todos }}
        display-lines: true
        root-directory: ${{ inputs.project-directory }}

    - name: Print confirmation message
      shell: bash
      run: echo "✅npm package source files verified!"
