name: Tag and release
description: Creates a Git tag and a GitHub release, from a Git branch named according to semver.

inputs:
  draft-only:
    description: Only draft the release.
    required: false
    default: false

  delete-branch:
    description: Deletes the branch after creating the tag.
    required: false
    default: true

  shell:
    description: The shell used to run commands.
    required: false
    default: bash

runs:
  using: composite
  steps:
    - name: Detect branch and version
      id: detect-branch-version
      uses: giancosta86/aurora-github/detect-branch-and-version@b2.0.0

    - name: Create Git tag
      id: create-git-tag
      shell: ${{ inputs.shell }}
      run: |
        version="${{ steps.detect-branch-version.outputs.version }}"

        tag="v${version}"
        echo "Creating Git tag '$tag'..."
        git tag "v${{ steps.detect-version.outputs.version }}"

        echo "tag=$tag" >> $GITHUB_OUTPUT

    - name: Delete Git branch
      if: ${{ inputs.delete-branch == 'true' }}
      shell: ${{ inputs.shell }}
      run: |
        branch="${{ steps.detect-branch-version.outputs.branch }}"

        echo "Deleting Git branch '$branch'..."

        git push origin --delete "$branch"

    - name: Create or draft release
      shell: ${{ inputs.shell }}
      run: |
        draftOnly="${{ inputs.draft-only }}"
        version="${{ steps.detect-branch-version.outputs.version }}"
        tag="${{ steps.create-git-tag.outputs.tag }}" 

        repoBasename="$(basename "$GITHUB_REPOSITORY")"
        releaseTitle="$repoBasename $version"        

        releaseRecap="release '$releaseTitle' from tag '$tag'"

        if [[ $draftOnly = "true" ]]
        then
          echo "Drafting $releaseRecap..."
          gh release create "$tag" --title "$releaseTitle" --draft
        else 
          echo "Creating $releaseRecap..."
          gh release create "$tag" --title "$releaseTitle"
        fi
