name: Tag and release
description: Creates a Git tag and a GitHub draft release when merging a pull request, in addition to updating a major version branch, from a Git branch named according to semantic versioning.

inputs:
  product-name:
    description: Name of the product; if empty, defaults to the repository name.

  update-major-branch:
    description: Create/update the 'v<major>' branch.
    default: true

outputs:
  tag:
    description: Git tag created for the release.
    value: ${{ steps.main.outputs.tag }}

  major-branch:
    description: Git branch of the major version, if updated.
    value: ${{ steps.main.outputs.major-branch }}

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "🍄🍄🍄 ACTION REPOSITORY IN T-A-R IS: '"${{ github.action_repository }}"'"

    - uses: giancosta86/gauntlet/actions/setup-elvish-action@v1
      with:
        core-repository: ${{ github.action_repository }}
        core-directory: ${{ github.action_path }}/../../core

    - if: github.event_name != 'pull_request' || github.event.action != 'closed' || github.event.pull_request.merged != true
      shell: elvish {0}
      run: |
        use github.com/giancosta86/aurora-github/actions/tag-and-release
        tag-and-release:skip

    - id: main
      if: env.skip != 'true'
      shell: elvish {0}
      run: |
        use github.com/giancosta86/aurora-github/actions/tag-and-release
        tag-and-release:main
      env:
        product-name: ${{ inputs.product-name }}
        update-major-branch: ${{ inputs.update-major-branch }}
        GH_TOKEN: ${{ github.token }}
