name: Tag and release
description: From a Git branch named according to semver, creates a Git tag and a GitHub release.

inputs:
  draft-only:
    description: Only draft the release.
    required: false
    default: false

  delete-branch:
    description: Delete the branch after creating the tag.
    required: false
    default: true

  shell:
    description: The shell used to run commands.
    required: false
    default: bash

runs:
  using: composite
  steps:
    - name: Detect branch and version
      id: detect-branch-version

    - name: Create Git tag
      id: create-git-tag
      shell: ${{ inputs.shell }}
      run: |
        version="${{ steps.detect-branch-version.outputs.version }}"

        tag="v${version}"
        echo "Creating tag '$tag'..."        
        echo "tag=$tag" >> $GITHUB_OUTPUT

      # git tag "v${{ steps.detect-version.outputs.version }}"

    - name: Delete branch
      shell: ${{ inputs.shell }}
      if: ${{ inputs.delete-branch == 'true' }}
      run: |
        branch="${{ steps.detect-branch.outputs.branch }}"

        echo "Deleting branch '$branch'..."

      # git push origin --delete "$branch"

    - name: Create or draft release
      shell: ${{ inputs.shell }}
      run: |
        draft_only="${{ inputs.draft-only }}"
        version="${{ steps.detect-branch-version.outputs.version }}"
        tag="${{ steps.create-git-tag.outputs.tag }}" 

        repo_basename="$(basename "$GITHUB_REPOSITORY")"
        release_title="$repo_basename $version"        

        release_recap="release '$release_title' from tag '$tag'"

        if [[ $draft_only = "true" ]]
        then
          echo "Drafting $release_recap..."
        else 
          echo "Creating $release_recap..."
        fi

    #  run: |
    #    gh release create "$source_tag" --draft --title "$release_title"
