name: Tag and release
description: From a versioned branch, creates a tag and a release

inputs:
  shell:
    description: The shell used to run commands
    required: false
    default: bash

  delete-branch:
    description: If set to 'true', deletes the branch
    required: false
    default: true

  draft-only:
    description: If set to 'true', only drafts the release
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Detect branch
      id: detect-branch
      shell: ${{ inputs.shell }}
      run: |
        branch="${{ github.head_ref }}"
        echo "Detected branch: '$branch'"        
        echo "branch=$branch" >> $GITHUB_OUTPUT

    - name: Detect version from branch
      id: detect-version
      shell: ${{ inputs.shell }}
      run: |
        branch="${{ steps.detect-branch.outputs.branch }}"
        version="$(echo "$branch" | sed 's/^b//')"
        echo "Detected version: '$version'"        
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Create tag
      id: create-tag
      shell: ${{ inputs.shell }}
      run: |
        version="${{ steps.detect-version.outputs.version }}"

        tag="v${version}"
        echo "Creating tag '$tag'..."
        echo "tag=$tag" >> $GITHUB_OUTPUT

    - name: Optionally delete branch
      shell: ${{ inputs.shell }}
      if: ${{ inputs.delete-branch == 'true' }}
      run: |
        branch="${{ steps.detect-branch.outputs.branch }}"
        echo "Deleting branch '$branch'..."

      # git tag "v${{ steps.detect-version.outputs.version }}"
      # git push origin --delete "$branch"

    - name: Create or draft release
      shell: ${{ inputs.shell }}
      run: |
        draft_only="${{ inputs.draft-only }}"
        version="${{ steps.detect-version.outputs.version }}"
        tag="${{ steps.create-tag.outputs.tag }}" 

        repo_basename="$(basename "$GITHUB_REPOSITORY")"
        release_title="$repo_basename $version"        

        release_recap="release '$release_title' from tag '$tag'"

        if [[ $draft_only = "true" ]]
        then
          echo "Drafting $release_recap..."
        else 
          echo "Creating $release_recap..."
        fi

    #  run: |
    #    gh release create "$source_tag" --draft --title "$release_title"
