name: Tag and release
description: Creates a Git tag and a GitHub release, from a Git branch named according to semver.

inputs:
  draft-only:
    description: Only draft the release.
    required: false
    default: false

  shell:
    description: The shell used to run commands.
    required: false
    default: bash

runs:
  using: composite
  steps:
    - name: Detect branch and version
      id: detect-branch-version
      uses: giancosta86/aurora-github/actions/detect-branch-version@b2.0.0

    - name: Verify branch and version
      shell: ${{ inputs.shell }}
      run: |
        branch="${{ steps.detect-branch-version.outputs.branch }}"
        version="${{ steps.detect-branch-version.outputs.version }}"

        if [[ -z $branch ]]
        then
          echo "❌The current Git branch could not be detected" >&2
          exit 1
        fi

        if [[ -z $version ]]
        then
          echo "❌The current version could not be detected from the Git branch" >&2
          exit 1
        fi

    - name: Create Git tag
      id: create-git-tag
      shell: ${{ inputs.shell }}
      run: |
        version="${{ steps.detect-branch-version.outputs.version }}"

        tag="v${version}"
        echo "Creating Git tag '$tag'..."
        git tag "v${{ steps.detect-version.outputs.version }}"

        echo "tag=$tag" >> $GITHUB_OUTPUT

    - name: Create or draft release
      shell: ${{ inputs.shell }}
      run: |
        draftOnly="${{ inputs.draft-only }}"
        version="${{ steps.detect-branch-version.outputs.version }}"
        tag="${{ steps.create-git-tag.outputs.tag }}" 

        repoBasename="$(basename "$GITHUB_REPOSITORY")"
        releaseTitle="$repoBasename $version"        

        releaseRecap="release '$releaseTitle' from tag '$tag'"

        if [[ $draftOnly = "true" ]]
        then
          echo "Drafting $releaseRecap..."
          gh release create "$tag" --title "$releaseTitle" --draft
        else 
          echo "Creating $releaseRecap..."
          gh release create "$tag" --title "$releaseTitle"
        fi
