name: Tag and release
description: Creates a Git tag and a GitHub release from the current branch

inputs:
  draft:
    description: Draft the release - do not publish it.
    default: true

  product-name:
    description: The name of the product; if empty, defaults to the repository name

  update-major-branch:
    description: Create/update the 'vX' branch containing the related major version.
    default: true

runs:
  using: composite
  steps:
    - if: github.event_name != 'pull_request' || github.event.action != 'closed' || github.event.pull_request.merged != true
      shell: bash
      run: |
        echo 'EVENT NAME:' ${{github.event_name}}
        echo 'EVENT ACTION:' ${{github.event.action}}
        echo 'PR MERGED:' ${{github.event.pull_request.merged}}
        echo '💭 tag-and-release can only run when merging a pull request'
        echo skip=true >> GITHUB_ENV

    - if: env.skip != 'true'
      uses: giancosta86/aurora-github/actions/setup-elvish-context@v11.0.0

    - if: env.skip != 'true'
      shell: elvish {0}
      run: |
        use github.com/giancosta86/aurora-github/actions/tag-and-release
        tag-and-release:main
      env:
        draft: ${{ inputs.draft }}
        product-name: ${{ inputs.product-name }}
        update-major-branch: ${{ inputs.update-major-branch }}
        GH_TOKEN: ${{ github.token }}
