name: Test replace-regex-pattern
description: Tests for replace-regex-pattern.

runs:
  using: composite
  steps:
    - uses: ./actions/setup-elvish-context

    - shell: elvish {0}
      run: |
        echo 'alpha' > A.txt
        echo 'beta' > B.txt

    - shell: elvish {0}
      run: echo 🎭 Testing replacement with enumerated files...

    - uses: ./actions/replace-regex-pattern
      with:
        files: A.txt, B.txt
        regex: "([ae])"
        replacement: "*$1*"

    - uses: ./actions/run-velvet-code
      with:
        code: |
          >> 'Checking replacement with enumerated files' {
            to-lines < A.txt |
              should-be '*a*lph*a*'

            to-lines < B.txt |
              should-be 'b*e*t*a*'
          }

    - shell: elvish {0}
      run: echo 🎭 Testing replacement with wildcard...

    - uses: ./actions/replace-regex-pattern
      with:
        files: "*.txt"
        regex: "\\*"
        replacement: ""

    - uses: ./actions/run-velvet-code
      with:
        code: |
          >> 'Checking replacement with wildcard' {
            to-lines < A.txt |
              should-be 'alpha'

            to-lines < B.txt |
              should-be 'beta'
          }
