name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./actions/tag-and-release
        with:
          set-major-tag: true
          notes-file-processor: .github/process-release-notes.sh
          git-strategy: rebase
          draft-release: true
