name: Validate actions

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: main

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      #- uses: giancosta86/aurora-github/actions/check-action-references@v2

      - uses: ./.github/test-actions/test-detect-branch-version

      - name: Verify wasm-pack
        shell: bash
        run: |
          if ! which wasm-pack
          then
            echo "wasm-pack not installed!" >&2
            exit 1
          fi

      - uses: ./.github/test-actions/test-install-wasm-pack
