name: Validate actions

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: main

  workflow_dispatch:

jobs:
  check-preconditions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: giancosta86/aurora-github/actions/check-action-references@v2

  #test-detect-branch-version:
  #  runs-on: ubuntu-latest
  #  needs: check-preconditions
  #  steps:
  #    - uses: actions/checkout@v4
  #    - uses: ./.github/test-actions/test-detect-branch-version

  #test-install-wasm-pack:
  #  runs-on: ubuntu-latest
  #  needs: check-preconditions
  #  steps:
  #    - uses: actions/checkout@v4
  #    - uses: ./.github/test-actions/test-install-wasm-pack

  test-print-rust-info:
    runs-on: ubuntu-latest
    needs: check-preconditions
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/test-actions/test-print-rust-info

  validate:
    runs-on: ubuntu-latest
    needs:
      #  - test-detect-branch-version
      #  - test-install-wasm-pack
      - test-print-rust-info

    steps:
      - name: Test branch
        shell: bash
        run: echo "✅Validation complete!"
