name: Verify
description: Runs the entire test network for the project.

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: main
  workflow_dispatch:

jobs:
  test-run-elvish-tests:
    if: false
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-run-elvish-tests

  test-detect-branch-version:
    if: false
    runs-on: ubuntu-24.04
    needs: test-run-elvish-tests
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-detect-branch-version

  test-check-action-references:
    if: false
    runs-on: ubuntu-24.04
    needs: test-detect-branch-version
    steps:
      - uses: actions/checkout@v7
      - uses: ./actions/check-action-references

  test-fundamental-actions:
    if: false
    runs-on: ubuntu-24.04
    needs:
      - test-run-elvish-tests
      - test-detect-branch-version
      - test-check-action-references
    steps:
      - shell: bash
        run: echo '✅ All the fundamental actions are OK!'

  test-check-project-license:
    if: false
    runs-on: ubuntu-24.04
    needs: test-fundamental-actions
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-check-project-license

  test-find-regex-pattern:
    if: false
    runs-on: ubuntu-24.04
    needs: test-fundamental-actions
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-find-regex-pattern

  test-find-critical-todos:
    if: false
    runs-on: ubuntu-24.04
    needs: test-find-regex-pattern
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-find-critical-todos

  test-replace-regex-pattern:
    if: false
    runs-on: ubuntu-24.04
    needs: test-fundamental-actions
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-replace-regex-pattern

  test-inject-branch-version:
    if: false
    runs-on: ubuntu-24.04
    needs: test-replace-regex-pattern
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-inject-branch-version

  test-install-system-packages:
    if: false
    runs-on: ubuntu-24.04
    needs: test-fundamental-actions
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-install-system-packages

  test-install-via-sdkman:
    if: false
    runs-on: ubuntu-24.04
    needs: test-fundamental-actions
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-install-via-sdkman

  test-upload-release-assets:
    if: false
    runs-on: ubuntu-24.04
    needs: test-fundamental-actions
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-upload-release-assets

  test-verify-elvish-package:
    if: false
    runs-on: ubuntu-24.04
    needs:
      - test-check-project-license
      - test-inject-branch-version
      - test-find-critical-todos
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-verify-elvish-package

  test-setup-rust-context:
    if: false
    runs-on: ubuntu-24.04
    needs: test-fundamental-actions
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-setup-rust-context

  test-verify-rust-crate:
    if: false
    runs-on: ubuntu-24.04
    needs:
      - test-check-project-license
      - test-inject-branch-version
      - test-setup-rust-context
      - test-find-critical-todos
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-verify-rust-crate

  test-publish-rust-crate:
    if: false
    runs-on: ubuntu-24.04
    needs:
      - test-setup-rust-context
      - test-inject-branch-version
      - test-verify-rust-crate
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-publish-rust-crate

  test-setup-nodejs-context:
    if: false
    runs-on: ubuntu-24.04
    needs: test-fundamental-actions
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-setup-nodejs-context

  test-check-subpath-exports:
    if: false
    runs-on: ubuntu-24.04
    needs: test-setup-nodejs-context
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-check-subpath-exports

  test-verify-npm-package:
    if: always()
    runs-on: ubuntu-24.04
    needs:
      - test-check-project-license
      - test-find-critical-todos
      - test-inject-branch-version
      - test-setup-nodejs-context
      - test-check-subpath-exports
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-verify-npm-package

  test-publish-npm-package:
    if: false
    runs-on: ubuntu-24.04
    needs:
      - test-inject-branch-version
      - test-setup-nodejs-context
      - test-verify-npm-package
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-publish-npm-package

  test-verify-rust-wasm:
    if: false
    runs-on: ubuntu-24.04
    needs:
      - test-check-project-license
      - test-verify-rust-crate
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-verify-rust-wasm

  test-publish-rust-wasm:
    if: false
    runs-on: ubuntu-24.04
    needs:
      - test-publish-npm-package
      - test-verify-rust-wasm
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-publish-rust-wasm

  test-verify-python-package:
    if: false
    runs-on: ubuntu-24.04
    needs:
      - test-check-project-license
      - test-find-critical-todos
      - test-inject-branch-version
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-verify-python-package

  test-publish-python-package:
    if: false
    runs-on: ubuntu-24.04
    needs:
      - test-inject-branch-version
      - test-verify-python-package
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-publish-python-package
        with:
          index-secret: FAKE-SECRET

  test-verify-jvm-project:
    if: false
    runs-on: ubuntu-24.04
    needs:
      - test-check-project-license
      - test-find-critical-todos
      - test-inject-branch-version
      - test-install-via-sdkman
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-verify-jvm-project

  test-publish-jvm-project:
    if: false
    runs-on: ubuntu-24.04
    needs:
      - test-inject-branch-version
      - test-install-via-sdkman
      - test-verify-jvm-project
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-publish-jvm-project
        with:
          jvm-token: FAKE_TOKEN

  test-publish-github-pages:
    if: false
    runs-on: ubuntu-24.04
    needs:
      - test-verify-npm-package
      - test-inject-branch-version
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-publish-github-pages

  test-tag-and-release:
    if: false
    runs-on: ubuntu-24.04
    needs: test-fundamental-actions
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/test-actions/test-tag-and-release

  verify:
    if: always()
    runs-on: ubuntu-24.04
    needs:
      - test-run-elvish-tests
      - test-detect-branch-version
      - test-check-action-references
      - test-fundamental-actions
      - test-check-project-license
      - test-find-regex-pattern
      - test-find-critical-todos
      - test-replace-regex-pattern
      - test-inject-branch-version
      - test-install-system-packages
      - test-install-via-sdkman
      - test-upload-release-assets
      - test-verify-elvish-package
      - test-setup-rust-context
      - test-verify-rust-crate
      - test-publish-rust-crate
      - test-setup-nodejs-context
      - test-check-subpath-exports
      - test-verify-npm-package
      - test-publish-npm-package
      - test-verify-rust-wasm
      - test-publish-rust-wasm
      - test-verify-python-package
      - test-publish-python-package
      - test-verify-jvm-project
      - test-publish-jvm-project
      - test-publish-github-pages
      - test-tag-and-release
    steps:
      - uses: actions/checkout@v7
      - uses: ./actions/check-required-jobs
        with:
          needs-as-json: ${{ toJSON(needs) }}
